import {NextResponse} from 'next/server';
import {createClient as createAdminClient} from '@supabase/supabase-js';
import {createClient as createSessionClient} from '@/lib/supabase/server';
import {liveModules} from '@/lib/live-modules';
export const dynamic='force-dynamic';
type Row=Record<string,any>;
function message(e:unknown){return e instanceof Error?e.message:(e&&typeof e==='object'&&'message'in e?String((e as {message:unknown}).message):'Database request failed.');}
function slug(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,100)||`record-${Date.now()}`;}
async function context(){const session=await createSessionClient();if(!session)throw new Error('Supabase session client is not configured.');const {data:{user}}=await session.auth.getUser();if(!user)throw Object.assign(new Error('Not authenticated.'),{status:401});const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw Object.assign(new Error('Supabase service credentials are not configured.'),{status:503});const admin=createAdminClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const {data:staff}=await admin.from('staff_members').select('id,status').or(`auth_user_id.eq.${user.id}${user.email?`,email.ilike.${user.email}`:''}`).limit(1).maybeSingle();if(!staff||String(staff.status).toLowerCase()==='disabled')throw Object.assign(new Error('Enterprise staff access is required.'),{status:403});return {admin,user};}
function clean(module:string,input:Row,creating=false):Row{const now=new Date().toISOString();switch(module){
case'projects':return {title:String(input.title||input.name||'').trim(),name:String(input.title||input.name||'').trim(),type:input.type||null,owner:input.owner||null,department:input.department||null,start_date:input.start_date||null,deadline:input.deadline||null,budget:input.budget===''||input.budget==null?null:Number(input.budget),objective:input.objective||null,status:input.status||'planning',updated_at:now};
case'analytics':return {name:String(input.name||'').trim(),department:String(input.department||'Operations').trim(),format:String(input.format||'dashboard').trim(),date_range:input.date_range||null};
case'contracts':return {contract_number:String(input.contract_number||'').trim(),project_id:input.project_id,creator_id:input.creator_id,project_title:String(input.project_title||'').trim(),currency:input.currency||'GBP',total_amount:Number(input.total_amount||0),start_date:input.start_date||null,end_date:input.end_date||null,status:input.status||'draft',updated_at:now};
case'assets':return {title:String(input.title||'').trim(),description:input.description||null,asset_type:String(input.asset_type||'').trim(),project_id:input.project_id||null,isrc:input.isrc||null,upc:input.upc||null,iswc:input.iswc||null,other_identifiers:input.other_identifiers||null,internal_identifier:input.internal_identifier||null,master_owner:input.master_owner||null,release_date:input.release_date||null,rights_start:input.rights_start||null,rights_end:input.rights_end||null,artwork_url:input.artwork_url||null,contract_confirmed:Boolean(input.contract_confirmed),contributors:Array.isArray(input.contributors)?input.contributors:[],status:input.status||'draft',restrictions:input.restrictions||null,updated_at:now};
case'experiences':{const assetIds=Array.isArray(input.asset_ids)?input.asset_ids:String(input.asset_ids_text||'').split(',').map((x:string)=>x.trim()).filter(Boolean);const pool=input.contributor_pool_percentage===''||input.contributor_pool_percentage==null?0:Number(input.contributor_pool_percentage);return {title:String(input.title||'').trim(),slug:input.slug||slug(String(input.title||'')),description:input.description||null,target_audience:input.target_audience||null,artwork_url:input.artwork_url||null,budget:input.budget===''||input.budget==null?null:Number(input.budget),director:input.director||null,contributor_pool_percentage:pool,asset_ids:assetIds,asset_count:assetIds.length,asset_share_percentage:assetIds.length?pool/assetIds.length:0,status:input.status||'draft',published_at:input.published_at?new Date(input.published_at).toISOString():null};}
case'content':return {title:String(input.title||'').trim(),slug:input.slug||slug(String(input.title||'')),content_type:String(input.content_type||'audio').trim(),description:input.description||null,artwork_url:input.artwork_url||null,media_url:input.media_url||null,preview_url:input.preview_url||null,release_at:input.release_at?new Date(input.release_at).toISOString():null,duration_seconds:input.duration_seconds===''||input.duration_seconds==null?null:Number(input.duration_seconds),status:input.status||'draft',updated_at:now};
case'newsroom':return {title:String(input.title||'').trim(),slug:input.slug||slug(String(input.title||'')),category:input.category||null,author_name:input.author_name||null,scheduled_for:input.scheduled_for?new Date(input.scheduled_for).toISOString():null,published_at:input.published_at?new Date(input.published_at).toISOString():(input.status==='published'?now:null),status:input.status||'draft',excerpt:input.excerpt||null,body:input.body||'',cover_image_url:input.cover_image_url||null,featured:String(input.featured)==='true'||input.featured===true,seo_title:input.seo_title||null,seo_description:input.seo_description||null,updated_at:now};
case'marketing':return {name:String(input.name||'').trim(),project_scope:input.project_scope||'experience',experience_id:input.project_scope==='external'?null:(input.experience_id||null),external_project_name:input.project_scope==='external'?(input.external_project_name||null):null,objective:input.objective||null,status:input.status||'draft',starts_at:input.starts_at?new Date(input.starts_at).toISOString():null,ends_at:input.ends_at?new Date(input.ends_at).toISOString():null,channels:Array.isArray(input.channels)?input.channels:String(input.channels_text||'').split(',').map((x:string)=>x.trim()).filter(Boolean),budget:input.budget===''||input.budget==null?null:Number(input.budget)};
case'finance':return {experience_id:input.experience_id,accounting_period:input.accounting_period,gross_revenue:Number(input.gross_revenue||0),distribution_cost:Number(input.distribution_cost||0),tax_withheld:Number(input.tax_withheld||0),platform_fees:Number(input.platform_fees||0),net_distributable:Number(input.net_distributable||0),creator_pool:Number(input.creator_pool||0),company_pool:Number(input.company_pool||0),status:input.status||'Approved'};
case'careers':return {title:String(input.title||'').trim(),slug:input.slug||slug(String(input.title||'')),department:input.department||null,location:input.location||null,employment_type:input.employment_type||null,summary:input.summary||null,description:input.description||'',requirements:input.requirements||'',application_url:input.application_url||null,hero_image_url:input.hero_image_url||null,seo_title:input.seo_title||null,seo_description:input.seo_description||null,closes_at:input.closes_at?new Date(input.closes_at).toISOString():null,status:input.status||'draft',updated_at:now};
case'support':return {name:String(input.name||'').trim(),email:String(input.email||'').trim(),topic:String(input.topic||'').trim(),message:String(input.message||'').trim(),category:input.category||'General enquiry',status:input.status||'new'};
case'crm':return {full_name:String(input.full_name||'').trim(),email:input.email||null,phone:input.phone||null,job_title:input.job_title||null,relationship_type:input.relationship_type||null,status:input.status||'active'};
case'website':case'pages':case'media':case'leadership':case'brand':return {...input,display_order:input.display_order===''||input.display_order==null?0:Number(input.display_order),updated_at:now};
case'navigation':return {...input,display_order:input.display_order===''||input.display_order==null?0:Number(input.display_order),open_new_tab:String(input.open_new_tab)==='true'||input.open_new_tab===true,updated_at:now};
case'events':return {...input,slug:input.slug||slug(String(input.title||'')),starts_at:input.starts_at?new Date(input.starts_at).toISOString():null,ends_at:input.ends_at?new Date(input.ends_at).toISOString():null,updated_at:now};
case'settings':return {name:String(input.name||'').trim(),description:input.description||null,...(creating?{permissions:[],is_system:false,is_master:false}:{}) ,updated_at:now};
default:return input;}}
function view(module:string,row:Row){if(module==='marketing')return {...row,channels_text:Array.isArray(row.channels)?row.channels.join(', '):'',experience_title:row.experience?.title||row.external_project_name||''};if(module==='experiences')return {...row,asset_ids_text:Array.isArray(row.asset_ids)?row.asset_ids.join(', '):''};return row;}
function responseError(e:any){return NextResponse.json({error:message(e)},{status:Number(e?.status)||500});}
export async function GET(_:Request,{params}:{params:Promise<{module:string}>}){try{const {module}=await params;const config=liveModules[module];if(!config)return NextResponse.json({error:'Unknown module.'},{status:404});const {admin}=await context();const selection=module==='marketing'?'*, experience:experiences(title)':'*';const {data,error}=await admin.from(config.table).select(selection).order('created_at',{ascending:false}).limit(500);if(error)throw error;return NextResponse.json({records:(data||[]).map(r=>view(module,r))});}catch(e){return responseError(e);}}
export async function POST(req:Request,{params}:{params:Promise<{module:string}>}){try{const {module}=await params;const config=liveModules[module];if(!config)return NextResponse.json({error:'Unknown module.'},{status:404});if(config.readOnly)return NextResponse.json({error:'This module is read-only.'},{status:405});const {admin,user}=await context();const body=await req.json();const row=clean(module,body,true);if(module==='analytics')row.created_by=user.id;if(module==='content'||module==='careers')row.created_by=user.id;if(module==='newsroom'){row.created_by=user.id;row.updated_by=user.id;}const {data,error}=await admin.from(config.table).insert(row).select('*').single();if(error)throw error;return NextResponse.json({record:view(module,data)});}catch(e){return responseError(e);}}
export async function PATCH(req:Request,{params}:{params:Promise<{module:string}>}){try{const {module}=await params;const config=liveModules[module];if(!config)return NextResponse.json({error:'Unknown module.'},{status:404});if(config.readOnly)return NextResponse.json({error:'This module is read-only.'},{status:405});const {admin,user}=await context();const body=await req.json();if(!body.id)return NextResponse.json({error:'Record ID is required.'},{status:400});const patch=clean(module,body,false);if(module==='newsroom')patch.updated_by=user.id;const {data,error}=await admin.from(config.table).update(patch).eq('id',body.id).select('*').single();if(error)throw error;return NextResponse.json({record:view(module,data)});}catch(e){return responseError(e);}}
export async function DELETE(req:Request,{params}:{params:Promise<{module:string}>}){try{const {module}=await params;const config=liveModules[module];if(!config)return NextResponse.json({error:'Unknown module.'},{status:404});if(config.readOnly)return NextResponse.json({error:'This module is read-only.'},{status:405});const {admin}=await context();const {id}=await req.json();if(!id)return NextResponse.json({error:'Record ID is required.'},{status:400});const {error}=await admin.from(config.table).delete().eq('id',id);if(error)throw error;return NextResponse.json({ok:true});}catch(e){return responseError(e);}}
