import {NextResponse} from 'next/server';
import {createClient as createAdminClient} from '@supabase/supabase-js';
import {createClient as createSessionClient} from '@/lib/supabase/server';
import {liveModules} from '@/lib/live-modules';
import {sendMail} from '@/lib/mail';
import {audit} from '@/lib/enterprise-auth';
export const dynamic='force-dynamic';
type Row=Record<string,any>;
function message(e:unknown){return e instanceof Error?e.message:(e&&typeof e==='object'&&'message'in e?String((e as {message:unknown}).message):'Database request failed.');}
function slug(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,100)||`record-${Date.now()}`;}
async function context(){const session=await createSessionClient();if(!session)throw new Error('Supabase session client is not configured.');const {data:{user}}=await session.auth.getUser();if(!user)throw Object.assign(new Error('Not authenticated.'),{status:401});const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw Object.assign(new Error('Supabase service credentials are not configured.'),{status:503});const admin=createAdminClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const {data:staff}=await admin.from('staff_members').select('id,status').or(`auth_user_id.eq.${user.id}${user.email?`,email.ilike.${user.email}`:''}`).limit(1).maybeSingle();if(!staff||String(staff.status).toLowerCase()==='disabled')throw Object.assign(new Error('Enterprise staff access is required.'),{status:403});return {admin,user,staff};}
function clean(module:string,input:Row,creating=false):Row{const now=new Date().toISOString();switch(module){
case'projects':{const projectTitle=String(input.title||input.name||'').trim();return {title:projectTitle,name:projectTitle,slug:input.slug||(creating?`${slug(projectTitle)}-${Date.now().toString(36)}`:undefined),project_type:input.project_type||null,asset_type:input.asset_type||'other',genre:input.genre||null,mood:input.mood||null,description:input.description||null,pay_amount:input.pay_amount===''||input.pay_amount==null?null:Number(input.pay_amount),pay_currency:input.pay_currency||'GBP',pay_notes:input.pay_notes||null,application_opens_at:input.application_opens_at?new Date(input.application_opens_at).toISOString():null,application_closes_at:input.application_closes_at?new Date(input.application_closes_at).toISOString():null,production_mode:input.production_mode||'open_application',commission_slots:Number(input.commission_slots||1),status:input.status||'planning',updated_at:now};}
case'analytics':return {name:String(input.name||'').trim(),department:String(input.department||'Operations').trim(),format:String(input.format||'dashboard').trim(),date_range:input.date_range||null};
case'contracts':{const perpetual=input.duration_mode==='perpetual';return {contract_number:String(input.contract_number||'').trim(),title:input.title||null,contract_type:input.contract_type||'creator_contribution',project_id:input.project_id||null,asset_id:input.asset_id||null,creator_id:input.creator_id||null,counterparty_name:input.counterparty_name||null,counterparty_email:input.counterparty_email||null,currency:input.currency||'GBP',total_amount:Number(input.total_amount||0),effective_at:input.effective_at||null,expires_at:perpetual?null:(input.expires_at||null),start_date:input.effective_at||null,end_date:perpetual?null:(input.expires_at||null),signed_document_url:input.signed_document_url||null,status:input.status||'draft',sent_at:(input.status==='sent'?(input.sent_at||now):input.sent_at||null),content:{introduction:`This agreement is between Plekxa Group Limited and ${input.counterparty_name||'the Creator'} for the project described below.`,scope:input.scope||'',deliverables:String(input.deliverables_text||'').split('\n').map((x:string)=>x.trim()).filter(Boolean),paymentTerms:input.payment_terms||'',intellectualProperty:input.intellectual_property||'',confidentiality:input.confidentiality||'',termination:input.termination||'',additionalTerms:input.additional_terms||'',durationMode:perpetual?'perpetual':'fixed_term'},notes:input.notes||null,updated_at:now};}
case'assets':return {title:String(input.title||'').trim(),description:input.description||null,asset_type:String(input.asset_type||'').trim(),genre:input.genre||null,mood:input.mood||null,index_id:input.index_id||null,profile_id:input.profile_id||null,project_id:input.project_id||null,isrc:input.isrc||null,upc:input.upc||null,iswc:input.iswc||null,other_identifiers:input.other_identifiers||null,internal_identifier:input.internal_identifier||null,master_owner:input.master_owner||null,release_date:input.release_date||null,rights_start:input.rights_start||null,rights_end:input.rights_end||null,artwork_url:input.artwork_url||null,contract_confirmed:Boolean(input.contract_confirmed),contributors:Array.isArray(input.contributors)?input.contributors:[],status:input.status||'draft',restrictions:input.restrictions||null,updated_at:now};
case'indexes':return {...input,index_code:String(input.index_code||'').trim(),name:String(input.name||'').trim(),year:Number(input.year||new Date().getFullYear()),target_asset_count:Number(input.target_asset_count||20),status:input.status||'planning',updated_at:now};}
case'profiles':return {...input,name:String(input.name||'').trim(),slug:input.slug||slug(String(input.name||'')),status:input.status||'active',updated_at:now};
case'releases':return {...input,asset_id:input.asset_id||null,profile_id:input.profile_id||null,release_date:input.release_date||null,status:input.status||'planned',updated_at:now};
case'collections':return {...input,collection_code:String(input.collection_code||'').trim(),title:String(input.title||'').trim(),slug:input.slug||slug(String(input.title||'')),profile_id:input.profile_id||null,status:input.status||'draft',updated_at:now};
case'certificates':return {...input,certificate_code:String(input.certificate_code||'').trim(),asset_id:input.asset_id||null,index_id:input.index_id||null,participation_percentage:Number(input.participation_percentage||0),effective_inclusion_date:input.effective_inclusion_date||null,status:input.status||'draft',updated_at:now};
case'content':return {title:String(input.title||'').trim(),slug:input.slug||slug(String(input.title||'')),content_type:String(input.content_type||'audio').trim(),description:input.description||null,artwork_url:input.artwork_url||null,media_url:input.media_url||null,preview_url:input.preview_url||null,release_at:input.release_at?new Date(input.release_at).toISOString():null,duration_seconds:input.duration_seconds===''||input.duration_seconds==null?null:Number(input.duration_seconds),status:input.status||'draft',updated_at:now};
case'newsroom':return {title:String(input.title||'').trim(),slug:input.slug||slug(String(input.title||'')),category:input.category||null,author_name:input.author_name||null,scheduled_for:input.scheduled_for?new Date(input.scheduled_for).toISOString():null,published_at:input.published_at?new Date(input.published_at).toISOString():(input.status==='published'?now:null),status:input.status||'draft',excerpt:input.excerpt||null,body:input.body||'',cover_image_url:input.cover_image_url||null,featured:String(input.featured)==='true'||input.featured===true,seo_title:input.seo_title||null,seo_description:input.seo_description||null,updated_at:now};
case'marketing':return {name:String(input.name||'').trim(),project_scope:input.project_scope||'external',asset_id:input.asset_id||null,collection_id:input.collection_id||null,profile_id:input.profile_id||null,external_project_name:input.project_scope==='external'?(input.external_project_name||null):null,objective:input.objective||null,status:input.status||'draft',starts_at:input.starts_at?new Date(input.starts_at).toISOString():null,ends_at:input.ends_at?new Date(input.ends_at).toISOString():null,channels:Array.isArray(input.channels)?input.channels:String(input.channels_text||'').split(',').map((x:string)=>x.trim()).filter(Boolean),budget:input.budget===''||input.budget==null?null:Number(input.budget)};
case'finance':return {asset_id:input.asset_id,period_start:input.period_start,period_end:input.period_end,source:input.source||null,gross_revenue:Number(input.gross_revenue||0),distribution_fees:Number(input.distribution_fees||0),collection_fees:Number(input.collection_fees||0),banking_fees:Number(input.banking_fees||0),transaction_fees:Number(input.transaction_fees||0),taxes:Number(input.taxes||0),direct_third_party_costs:Number(input.direct_third_party_costs||0),currency:input.currency||'GBP',status:input.status||'draft'};
case'careers':return {title:String(input.title||'').trim(),slug:input.slug||slug(String(input.title||'')),department:input.department||null,location:input.location||null,employment_type:input.employment_type||null,summary:input.summary||null,description:input.description||'',requirements:input.requirements||'',application_url:input.application_url||null,hero_image_url:input.hero_image_url||null,seo_title:input.seo_title||null,seo_description:input.seo_description||null,closes_at:input.closes_at?new Date(input.closes_at).toISOString():null,status:input.status||'draft',updated_at:now};
case'support':return {name:String(input.name||'').trim(),email:String(input.email||'').trim(),topic:String(input.topic||'').trim(),message:String(input.message||'').trim(),category:input.category||'General enquiry',status:input.status||'new'};

case'crm':return {full_name:String(input.full_name||'').trim(),email:input.email||null,phone:input.phone||null,job_title:input.job_title||null,relationship_type:input.relationship_type||null,status:input.status||'active'};
case'website':case'pages':case'media':case'leadership':case'brand':return {...input,display_order:input.display_order===''||input.display_order==null?0:Number(input.display_order),updated_at:now};
case'navigation':return {...input,display_order:input.display_order===''||input.display_order==null?0:Number(input.display_order),open_new_tab:String(input.open_new_tab)==='true'||input.open_new_tab===true,updated_at:now};
case'events':return {...input,slug:input.slug||slug(String(input.title||'')),starts_at:input.starts_at?new Date(input.starts_at).toISOString():null,ends_at:input.ends_at?new Date(input.ends_at).toISOString():null,updated_at:now};
case'settings':return {name:String(input.name||'').trim(),description:input.description||null,...(creating?{permissions:[],is_system:false,is_master:false}:{}) ,updated_at:now};
default:return input;}}
function view(module:string,row:Row){if(module==='creatorprofiles')return {...row,display_name:row.stage_name||row.full_name||row.legal_name||row.name||row.email||'Creator'};if(module==='marketing')return {...row,channels_text:Array.isArray(row.channels)?row.channels.join(', '):''};if(module==='finance')return {...row,accounting_period_label:[row.accounting_period_start||row.accounting_period,row.accounting_period_end].filter(Boolean).join(' – ')};if(module==='contracts'){const c=row.content||{};return {...row,duration_mode:c.durationMode||(row.expires_at||row.end_date?'fixed_term':'perpetual'),scope:c.scope||'',deliverables_text:Array.isArray(c.deliverables)?c.deliverables.join('\n'):'',payment_terms:c.paymentTerms||'',intellectual_property:c.intellectualProperty||'',confidentiality:c.confidentiality||'',termination:c.termination||'',additional_terms:c.additionalTerms||''}}return row;}
function responseError(e:any){return NextResponse.json({error:message(e)},{status:Number(e?.status)||500});}
export async function GET(_:Request,{params}:{params:Promise<{module:string}>}){try{const {module}=await params;const config=liveModules[module];if(!config)return NextResponse.json({error:'Unknown module.'},{status:404});const {admin}=await context();const selection='*';const {data,error}=await admin.from(config.table).select(selection).order('created_at',{ascending:false}).limit(500);if(error)throw error;return NextResponse.json({records:(data||[]).map(r=>view(module,r))});}catch(e){return responseError(e);}}
export async function POST(req:Request,{params}:{params:Promise<{module:string}>}){try{const {module}=await params;const config=liveModules[module];if(!config)return NextResponse.json({error:'Unknown module.'},{status:404});if(config.readOnly)return NextResponse.json({error:'This module is read-only.'},{status:405});const {admin,user,staff}=await context();const body=await req.json();const row=clean(module,body,true);if(module==='analytics')row.created_by=user.id;if(module==='content'||module==='careers')row.created_by=user.id;if(module==='newsroom'){row.created_by=user.id;row.updated_by=user.id;}if(module==='contracts'&&row.project_id&&!row.asset_id){const {data:pr}=await admin.from('projects').select('reserved_asset_id').eq('id',row.project_id).maybeSingle();row.asset_id=pr?.reserved_asset_id||null;}if(module==='contracts'&&row.creator_id){const {data:cp}=await admin.from('creator_profiles').select('user_id,legal_name,stage_name,email').eq('id',row.creator_id).maybeSingle();if(!row.counterparty_name)row.counterparty_name=cp?.legal_name||cp?.stage_name||null;if(!row.counterparty_email)row.counterparty_email=cp?.email||null;row.creator_user_id=cp?.user_id||null;}const {data,error}=await admin.from(config.table).insert(row).select('*').single();if(error)throw error;if(module==='projects'){const {data:reservation,error:reserveError}=await admin.rpc('plekxa_reserve_project_asset',{p_project_id:data.id});if(reserveError){await admin.from('projects').delete().eq('id',data.id);throw new Error(`Project could not reserve its Asset/Index: ${reserveError.message}`)}const r=Array.isArray(reservation)?reservation[0]:reservation;if(r){data.reserved_asset_id=r.asset_id;data.index_id=r.index_id;data.asset_code=r.asset_code;data.index_code=r.index_code;}}await audit(admin,user,staff,'created',config.table,String(data.id),{after:data});if(module==='contracts'&&data.creator_id&&data.status==='sent'){const {data:cp}=await admin.from('creator_profiles').select('user_id').eq('id',data.creator_id).maybeSingle();if(cp?.user_id)await admin.from('notifications').insert({recipient_id:cp.user_id,audience:'creator',type:'contract_sent',title:'New contract from Plekxa',message:`${data.title||'A contract'} is ready for your review and signature.`,action_url:`/contracts/${data.id}`,entity_type:'contract',entity_id:data.id,metadata:{contract_number:data.contract_number,project_id:data.project_id}});if(data.counterparty_email)await sendMail({to:data.counterparty_email,subject:'New Plekxa contract ready for signature',text:`${data.title||'Your contract'} is ready in Plekxa Creator Studio.`}).catch(()=>null)}return NextResponse.json({record:view(module,data)});}catch(e){return responseError(e);}}
export async function PATCH(req:Request,{params}:{params:Promise<{module:string}>}){try{const {module}=await params;const config=liveModules[module];if(!config)return NextResponse.json({error:'Unknown module.'},{status:404});if(config.readOnly)return NextResponse.json({error:'This module is read-only.'},{status:405});const {admin,user,staff}=await context();const body=await req.json();if(!body.id)return NextResponse.json({error:'Record ID is required.'},{status:400});const patch=clean(module,body,false);if(module==='newsroom')patch.updated_by=user.id;if(module==='contracts'&&patch.project_id&&!patch.asset_id){const {data:pr}=await admin.from('projects').select('reserved_asset_id').eq('id',patch.project_id).maybeSingle();patch.asset_id=pr?.reserved_asset_id||null;}if(module==='contracts'&&patch.creator_id){const {data:cp}=await admin.from('creator_profiles').select('user_id').eq('id',patch.creator_id).maybeSingle();patch.creator_user_id=cp?.user_id||null;}const {data,error}=await admin.from(config.table).update(patch).eq('id',body.id).select('*').single();if(error)throw error;await audit(admin,user,staff,'updated',config.table,String(data.id),{requested_changes:patch});if(module==='contracts'&&data.creator_id&&data.status==='sent'&&body.status==='sent'){const {data:cp}=await admin.from('creator_profiles').select('user_id').eq('id',data.creator_id).maybeSingle();if(cp?.user_id)await admin.from('notifications').insert({recipient_id:cp.user_id,audience:'creator',type:'contract_sent',title:'Contract ready for signature',message:`${data.title||'Your contract'} is ready in Creator Studio.`,action_url:`/contracts/${data.id}`,entity_type:'contract',entity_id:data.id,metadata:{contract_number:data.contract_number,project_id:data.project_id}});if(data.counterparty_email)await sendMail({to:data.counterparty_email,subject:'Plekxa contract ready for signature',text:`${data.title||'Your contract'} is ready in Plekxa Creator Studio.`}).catch(()=>null)}return NextResponse.json({record:view(module,data)});}catch(e){return responseError(e);}}
export async function DELETE(req:Request,{params}:{params:Promise<{module:string}>}){try{const {module}=await params;const config=liveModules[module];if(!config)return NextResponse.json({error:'Unknown module.'},{status:404});if(config.readOnly)return NextResponse.json({error:'This module is read-only.'},{status:405});const {admin,user,staff}=await context();const {id}=await req.json();if(!id)return NextResponse.json({error:'Record ID is required.'},{status:400});const {error}=await admin.from(config.table).delete().eq('id',id);if(error)throw error;await audit(admin,user,staff,'deleted',config.table,String(id),{});return NextResponse.json({ok:true});}catch(e){return responseError(e);}}
