import {NextResponse} from 'next/server';
import {createClient} from '@supabase/supabase-js';
import {liveModules} from '@/lib/live-modules';
export const dynamic='force-dynamic';
function db(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL;const k=process.env.SUPABASE_SERVICE_ROLE_KEY;return u&&k?createClient(u,k,{auth:{persistSession:false,autoRefreshToken:false}}):null}
function msg(e:unknown){return e instanceof Error?e.message:(e&&typeof e==='object'&&'message'in e?String((e as {message:unknown}).message):'Database request failed.')}
export async function GET(_:Request,{params}:{params:Promise<{module:string}>}){try{const {module}=await params;const s=db();if(!s)return NextResponse.json({error:'Supabase service credentials are not configured.'},{status:503});if(!liveModules[module])return NextResponse.json({error:'Unknown module.'},{status:404});if(module==='projects'){const {data,error}=await s.from('projects').select('*').order('created_at',{ascending:false});if(error)throw error;return NextResponse.json({records:data??[]})}const {data,error}=await s.from('enterprise_records').select('*').eq('module',module).order('created_at',{ascending:false});if(error)throw error;return NextResponse.json({records:(data??[]).map(r=>({id:r.id,...(r.data||{}),status:r.status,created_at:r.created_at,updated_at:r.updated_at}))})}catch(e){return NextResponse.json({error:msg(e)},{status:500})}}
export async function POST(req:Request,{params}:{params:Promise<{module:string}>}){try{const {module}=await params;const s=db();if(!s)return NextResponse.json({error:'Supabase service credentials are not configured.'},{status:503});const config=liveModules[module];if(!config)return NextResponse.json({error:'Unknown module.'},{status:404});const body=await req.json();if(module==='projects'){const row={title:body.title,name:body.title,type:body.type||null,owner:body.owner||null,department:body.department||null,start_date:body.start_date||null,deadline:body.deadline||null,budget:body.budget===''?null:Number(body.budget||0),objective:body.objective||null,status:body.status||'planning',updated_at:new Date().toISOString()};const {data,error}=await s.from('projects').insert(row).select('*').single();if(error)throw error;await s.from('enterprise_records').insert({module:'activity',status:'recorded',data:{title:`Project created: ${body.title}`,actor:'Enterprise OS',entity:'Projects',description:'Created through the live Enterprise OS.'}});return NextResponse.json({record:data})}const status=String(body.status||config.statuses[0]||'active');const {status:_s,id:_id,created_at:_c,updated_at:_u,...payload}=body;const {data,error}=await s.from('enterprise_records').insert({module,status,data:payload}).select('*').single();if(error)throw error;return NextResponse.json({record:{id:data.id,...data.data,status:data.status,created_at:data.created_at,updated_at:data.updated_at}})}catch(e){return NextResponse.json({error:msg(e)},{status:500})}}
export async function PATCH(req:Request,{params}:{params:Promise<{module:string}>}){try{const {module}=await params;const s=db();if(!s)return NextResponse.json({error:'Supabase service credentials are not configured.'},{status:503});if(!liveModules[module])return NextResponse.json({error:'Unknown module.'},{status:404});const body=await req.json();if(!body.id)return NextResponse.json({error:'Record ID is required.'},{status:400});if(module==='projects'){const {id,...patch}=body;patch.updated_at=new Date().toISOString();if(patch.title)patch.name=patch.title;const {data,error}=await s.from('projects').update(patch).eq('id',id).select('*').single();if(error)throw error;return NextResponse.json({record:data})}const {id,status,created_at,updated_at,...payload}=body;const {data:current,error:readError}=await s.from('enterprise_records').select('*').eq('id',id).eq('module',module).single();if(readError)throw readError;const {data,error}=await s.from('enterprise_records').update({status:status||current.status,data:{...(current.data||{}),...payload},updated_at:new Date().toISOString()}).eq('id',id).select('*').single();if(error)throw error;return NextResponse.json({record:{id:data.id,...data.data,status:data.status,created_at:data.created_at,updated_at:data.updated_at}})}catch(e){return NextResponse.json({error:msg(e)},{status:500})}}
export async function DELETE(req:Request,{params}:{params:Promise<{module:string}>}){try{const {module}=await params;const s=db();if(!s)return NextResponse.json({error:'Supabase service credentials are not configured.'},{status:503});const {id}=await req.json();if(!id)return NextResponse.json({error:'Record ID is required.'},{status:400});const table=module==='projects'?'projects':'enterprise_records';let q=s.from(table).delete().eq('id',id);if(table==='enterprise_records')q=q.eq('module',module);const {error}=await q;if(error)throw error;return NextResponse.json({ok:true})}catch(e){return NextResponse.json({error:msg(e)},{status:500})}}
