import {NextResponse} from 'next/server';
import {createClient as createAdminClient} from '@supabase/supabase-js';
import {createClient} from '@/lib/supabase/server';
import {PutObjectCommand,GetObjectCommand,DeleteObjectCommand,CreateMultipartUploadCommand,UploadPartCommand,CompleteMultipartUploadCommand,AbortMultipartUploadCommand} from '@aws-sdk/client-s3';
import {getSignedUrl} from '@aws-sdk/s3-request-presigner';
import {R2_BUCKET,r2Client,assetObjectKey} from '@/lib/r2';
export const dynamic='force-dynamic';
type Row=Record<string,any>; function msg(e:any){return e?.message||'File request failed.'} function err(e:any){return NextResponse.json({error:msg(e)},{status:e?.status||500})}
async function staff(){const session=await createClient();const {data:{user}}=await session.auth.getUser();if(!user)throw Object.assign(new Error('Not authenticated.'),{status:401});const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!u||!k)throw new Error('Supabase service credentials are not configured.');const s=createAdminClient(u,k,{auth:{persistSession:false}});const {data:member}=await s.from('staff_members').select('id,status').or(`auth_user_id.eq.${user.id}${user.email?`,email.ilike.${user.email}`:''}`).limit(1).maybeSingle();if(!member||String(member.status).toLowerCase()==='disabled')throw Object.assign(new Error('Enterprise staff access required.'),{status:403});return {s,user}}
const categoryFor=(x:string)=>['audio','video','artwork','stems','lyrics','document','other'].includes(x)?x:'other';
async function asset(s:any,id:string){const {data,error}=await s.from('asset_registry').select('id,internal_identifier').eq('id',id).single();if(error)throw error;if(!data.internal_identifier)throw new Error('Asset has no permanent AST identifier. Run migration 015.');return data}
export async function GET(r:Request){try{const {s}=await staff();const id=new URL(r.url).searchParams.get('asset_id');if(!id)return NextResponse.json({error:'asset_id is required.'},{status:400});const {data,error}=await s.from('asset_files').select('*').eq('asset_id',id).order('created_at',{ascending:false});if(error)throw error;const c=r2Client();const files=await Promise.all((data||[]).map(async(f:Row)=>{const key=f.r2_key||f.storage_path;if(!key)return f;return {...f,download_url:await getSignedUrl(c,new GetObjectCommand({Bucket:f.r2_bucket||R2_BUCKET,Key:key}),{expiresIn:900})}}));return NextResponse.json({files})}catch(e){return err(e)}}
export async function POST(r:Request){try{const {s,user}=await staff();const b=await r.json();const assetId=String(b.asset_id||'');if(!assetId)return NextResponse.json({error:'Asset is required.'},{status:400});const a=await asset(s,assetId), action=String(b.action||'presign'), client=r2Client();
 if(action==='presign'||action==='multipart-create'){const name=String(b.relative_path||b.file_name||'');const type=String(b.mime_type||'application/octet-stream');const size=Number(b.size_bytes||0);if(!name||size<=0)return NextResponse.json({error:'File name and size are required.'},{status:400});const key=assetObjectKey(a.internal_identifier,categoryFor(String(b.category||'other')),name);if(action==='presign'&&size<=5*1024**3){const upload_url=await getSignedUrl(client,new PutObjectCommand({Bucket:R2_BUCKET,Key:key,ContentType:type}),{expiresIn:3600});return NextResponse.json({mode:'single',upload_url,key,bucket:R2_BUCKET})}const created=await client.send(new CreateMultipartUploadCommand({Bucket:R2_BUCKET,Key:key,ContentType:type}));return NextResponse.json({mode:'multipart',upload_id:created.UploadId,key,bucket:R2_BUCKET,part_size:100*1024*1024})}
 if(action==='multipart-part'){const key=String(b.key||''),uploadId=String(b.upload_id||''),part=Number(b.part_number||0);if(!key.startsWith(`${a.internal_identifier}/`)||!uploadId||part<1||part>10000)return NextResponse.json({error:'Invalid multipart request.'},{status:400});const upload_url=await getSignedUrl(client,new UploadPartCommand({Bucket:R2_BUCKET,Key:key,UploadId:uploadId,PartNumber:part}),{expiresIn:3600});return NextResponse.json({upload_url})}
 if(action==='multipart-complete'){const key=String(b.key||''),uploadId=String(b.upload_id||'');if(!key.startsWith(`${a.internal_identifier}/`))return NextResponse.json({error:'Invalid object key.'},{status:400});await client.send(new CompleteMultipartUploadCommand({Bucket:R2_BUCKET,Key:key,UploadId:uploadId,MultipartUpload:{Parts:(b.parts||[]).map((x:any)=>({ETag:x.etag,PartNumber:Number(x.part_number)}))}}));return NextResponse.json({ok:true})}
 if(action==='multipart-abort'){await client.send(new AbortMultipartUploadCommand({Bucket:R2_BUCKET,Key:String(b.key),UploadId:String(b.upload_id)}));return NextResponse.json({ok:true})}
 if(action==='confirm'){const key=String(b.key||'');if(!key.startsWith(`${a.internal_identifier}/`))return NextResponse.json({error:'Invalid R2 object key.'},{status:400});const row={asset_id:assetId,file_name:String(b.file_name||key.split('/').pop()),storage_path:key,r2_key:key,r2_bucket:R2_BUCKET,storage_provider:'cloudflare_r2',public_url:null,mime_type:String(b.mime_type||'application/octet-stream'),size_bytes:Number(b.size_bytes||0),file_category:categoryFor(String(b.category||'other')),uploaded_by:user.id};const {data,error}=await s.from('asset_files').insert(row).select('*').single();if(error)throw error;await s.from('asset_registry').update({r2_master_prefix:`${a.internal_identifier}/`}).eq('id',assetId);return NextResponse.json({file:data})}
 return NextResponse.json({error:'Unknown action.'},{status:400})}catch(e){return err(e)}}
export async function DELETE(r:Request){try{const {s}=await staff();const {id}=await r.json();const {data,error}=await s.from('asset_files').select('*').eq('id',id).single();if(error)throw error;const key=data.r2_key||data.storage_path;if(key)await r2Client().send(new DeleteObjectCommand({Bucket:data.r2_bucket||R2_BUCKET,Key:key}));const {error:de}=await s.from('asset_files').delete().eq('id',id);if(de)throw de;return NextResponse.json({ok:true})}catch(e){return err(e)}}