import { NextResponse } from 'next/server';
import { createClient as createAdminClient } from '@supabase/supabase-js';
import { createClient as createSessionClient } from '@/lib/supabase/server';
import { DeleteObjectCommand, GetObjectCommand, PutObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { R2_BUCKET, assetObjectKey, r2Client } from '@/lib/r2';

export const dynamic='force-dynamic';
type Row=Record<string,any>;
function admin(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!u||!k)throw new Error('Supabase service credentials are not configured.');return createAdminClient(u,k,{auth:{persistSession:false,autoRefreshToken:false}})}
async function staff(){const session=await createSessionClient();const {data:{user}}=await session.auth.getUser();if(!user)throw Object.assign(new Error('Not authenticated.'),{status:401});const s=admin();const {data}=await s.from('staff_members').select('id,status').or(`auth_user_id.eq.${user.id}${user.email?`,email.ilike.${user.email}`:''}`).limit(1).maybeSingle();if(!data||String(data.status).toLowerCase()==='disabled')throw Object.assign(new Error('Enterprise staff access is required.'),{status:403});return {s,user}}
function categoryFor(category:string){return ['audio','video','artwork','stems','lyrics','document','other'].includes(category)?category:'other'}
function err(e:any){return NextResponse.json({error:e?.message||'File request failed.'},{status:e?.status||500})}

export async function GET(r:Request){try{const {s}=await staff();const id=new URL(r.url).searchParams.get('asset_id');if(!id)return NextResponse.json({error:'asset_id is required.'},{status:400});const {data,error}=await s.from('asset_files').select('*').eq('asset_id',id).order('created_at',{ascending:false});if(error)throw error;const client=r2Client();const files=await Promise.all((data||[]).map(async(f:Row)=>{const key=f.r2_key||f.storage_path;if(!key)return f;const download_url=await getSignedUrl(client,new GetObjectCommand({Bucket:f.r2_bucket||R2_BUCKET,Key:key}),{expiresIn:900});return {...f,download_url,public_url:download_url}}));return NextResponse.json({files})}catch(e){return err(e)}}

export async function POST(r:Request){try{const {s,user}=await staff();const body=await r.json();const action=String(body.action||'presign');const assetId=String(body.asset_id||'');if(!assetId)return NextResponse.json({error:'Asset is required.'},{status:400});
 const {data:asset,error:ae}=await s.from('asset_registry').select('id,internal_identifier,title').eq('id',assetId).single();if(ae)throw ae;const assetCode=String(asset.internal_identifier||`AST-${asset.id.replaceAll('-','').slice(0,12)}`);
 if(action==='presign'){const name=String(body.file_name||'');const type=String(body.mime_type||'application/octet-stream');const size=Number(body.size_bytes||0);if(!name||size<=0)return NextResponse.json({error:'File name and size are required.'},{status:400});if(size>5*1024*1024*1024)return NextResponse.json({error:'File exceeds the 5 GB single-upload limit.'},{status:400});const category=categoryFor(String(body.category||'other'));const key=assetObjectKey(assetCode,category,name);const upload_url=await getSignedUrl(r2Client(),new PutObjectCommand({Bucket:R2_BUCKET,Key:key,ContentType:type}),{expiresIn:900});return NextResponse.json({upload_url,key,bucket:R2_BUCKET,asset_code:assetCode,expires_in:900})}
 if(action==='confirm'){const key=String(body.key||'');if(!key||!key.startsWith(`${assetCode}/`))return NextResponse.json({error:'Invalid R2 object key.'},{status:400});const row={asset_id:assetId,file_name:String(body.file_name||key.split('/').pop()),storage_path:key,r2_key:key,r2_bucket:R2_BUCKET,storage_provider:'cloudflare_r2',public_url:null,mime_type:String(body.mime_type||'application/octet-stream'),size_bytes:Number(body.size_bytes||0),file_category:categoryFor(String(body.category||'other')),uploaded_by:user.id};const {data,error}=await s.from('asset_files').insert(row).select('*').single();if(error)throw error;await s.from('asset_registry').update({r2_master_prefix:`${assetCode}/`}).eq('id',assetId);return NextResponse.json({file:data})}
 return NextResponse.json({error:'Unknown action.'},{status:400});}catch(e){return err(e)}}

export async function DELETE(r:Request){try{const {s}=await staff();const {id}=await r.json();const {data,error}=await s.from('asset_files').select('*').eq('id',id).single();if(error)throw error;const key=data.r2_key||data.storage_path;if(key)await r2Client().send(new DeleteObjectCommand({Bucket:data.r2_bucket||R2_BUCKET,Key:key}));const {error:de}=await s.from('asset_files').delete().eq('id',id);if(de)throw de;return NextResponse.json({ok:true})}catch(e){return err(e)}}
