import {NextResponse} from 'next/server';
import {createClient as createAdminClient} from '@supabase/supabase-js';
import {createClient} from '@/lib/supabase/server';
import {GetObjectCommand,HeadObjectCommand} from '@aws-sdk/client-s3';
import {getSignedUrl} from '@aws-sdk/s3-request-presigner';
import {r2Client,R2_BUCKET} from '@/lib/r2';
export const dynamic='force-dynamic';
type Row=Record<string,any>;
async function staff(){const session=await createClient();const {data:{user}}=await session.auth.getUser();if(!user)throw Object.assign(new Error('Not authenticated.'),{status:401});const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!u||!k)throw new Error('Database not configured');const s=createAdminClient(u,k,{auth:{persistSession:false}});const {data:member}=await s.from('staff_members').select('id,status').or(`auth_user_id.eq.${user.id}${user.email?`,email.ilike.${user.email}`:''}`).limit(1).maybeSingle();if(!member||String(member.status).toLowerCase()==='disabled')throw Object.assign(new Error('Enterprise staff access required.'),{status:403});return{s}}
function missing(e:any){const code=String(e?.name||e?.Code||e?.code||'');const status=e?.$metadata?.httpStatusCode;return code==='NotFound'||code==='NoSuchKey'||status===404}
export async function GET(){try{const{s}=await staff();const{data:assets,error:ae}=await s.from('asset_registry').select('id,title,internal_identifier,status').in('status',['approved','active','Approved','Active']).order('created_at',{ascending:false});if(ae)throw ae;const ids=(assets||[]).map(a=>a.id);if(!ids.length)return NextResponse.json({files:[]});const{data:files,error}=await s.from('asset_files').select('*').in('asset_id',ids).order('created_at',{ascending:false});if(error)throw error;const c=r2Client();const out=await Promise.all((files||[]).map(async(f:Row)=>{const a=(assets||[]).find(x=>x.id===f.asset_id);const key=String(f.r2_key||f.storage_path||'');const bucket=String(f.r2_bucket||R2_BUCKET);let available=false,reason:string|null=null;if(!key)reason='No storage key is recorded.';else try{await c.send(new HeadObjectCommand({Bucket:bucket,Key:key}));available=true}catch(e:any){reason=missing(e)?'Source file is missing from R2. Re-upload it from the Asset Registry.':'Source file could not be verified.'}return{...f,asset_title:a?.title||'Asset',asset_code:a?.internal_identifier||'',asset_status:a?.status||'',source_available:available,source_issue:reason,download_path:available?`/api/marketing/approved-files/${f.id}`:null}}));return NextResponse.json({files:out})}catch(e:any){return NextResponse.json({error:e.message},{status:e?.status||500})}}
