import{NextResponse}from'next/server';import{createClient}from'@supabase/supabase-js';import{createClient as sessionClient}from'@/lib/supabase/server';
export const dynamic='force-dynamic';function db(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!u||!k)throw new Error('Database not configured');return createClient(u,k,{auth:{persistSession:false}})}
const n=(v:any)=>Number(v||0);const money=(v:number,c='GBP')=>new Intl.NumberFormat('en-GB',{style:'currency',currency:c,maximumFractionDigits:0}).format(v);
async function count(s:any,t:string,filter?:[string,string]){let q=s.from(t).select('id',{count:'exact',head:true});if(filter)q=q.eq(filter[0],filter[1]);const r=await q;if(r.error)throw r.error;return r.count||0}
async function statuses(s:any,t:string){const r=await s.from(t).select('status');if(r.error)throw r.error;const m:any={};for(const x of r.data||[])m[x.status||'unspecified']=(m[x.status||'unspecified']||0)+1;return Object.entries(m).sort((a:any,b:any)=>b[1]-a[1]).slice(0,6)}
async function months(s:any,t:string){const since=new Date();since.setMonth(since.getMonth()-11);since.setDate(1);since.setHours(0,0,0,0);const r=await s.from(t).select('created_at').gte('created_at',since.toISOString());if(r.error)return Array(12).fill(0);const out=Array(12).fill(0),now=new Date();for(const x of r.data||[]){const d=new Date(x.created_at),diff=(now.getFullYear()-d.getFullYear())*12+now.getMonth()-d.getMonth();if(diff>=0&&diff<12)out[11-diff]++}return out}
export async function GET(){try{const ss=await sessionClient();const{data:{user}}=await ss.auth.getUser();if(!user)return NextResponse.json({error:'Not authenticated'},{status:401});const s=db();const [creators,projects,assets,indexes,campaigns,tickets,contracts,applications,notifications]=await Promise.all([count(s,'creator_profiles'),count(s,'projects'),count(s,'asset_registry'),count(s,'plekxa_indexes'),count(s,'marketing_campaigns'),count(s,'support_requests'),count(s,'contracts'),count(s,'creator_applications'),count(s,'notifications')]);const[{data:rev},{data:alloc}]=await Promise.all([s.from('asset_revenue_entries').select('gross_revenue,net_distributable,currency,status'),s.from('creator_revenue_allocations').select('amount,currency,status')]);const gross=(rev||[]).reduce((a:any,x:any)=>a+n(x.gross_revenue),0),net=(rev||[]).reduce((a:any,x:any)=>a+n(x.net_distributable),0),payable=(alloc||[]).filter((x:any)=>x.status!=='paid').reduce((a:any,x:any)=>a+n(x.amount),0);const approved=await count(s,'asset_registry',['status','approved']),activeProjects=await count(s,'projects',['status','in_production']),openTickets=await count(s,'support_requests',['status','open']);const map:any={
'Company overview':{metrics:[['Creators',creators,'Live creator profiles'],['Projects',projects,'All project records'],['Assets',assets,'Reserved and registered Assets'],['Indexes',indexes,'Diversified Indexes']],table:'projects'},
'Executive':{metrics:[['Gross recorded revenue',money(gross),'Live finance ledger'],['Net distributable',money(net),'Live finance ledger'],['Active projects',activeProjects,'In production'],['Open support',openTickets,'Open requests']],table:'projects'},
'Creator Success':{metrics:[['Creator profiles',creators,'Live profiles'],['Applications',applications,'All applications'],['Contracts',contracts,'All contracts'],['Notifications',notifications,'Recorded notifications']],table:'creator_applications'},
'Projects':{metrics:[['Projects',projects,'All projects'],['In production',activeProjects,'Current status'],['Applications',applications,'Creator applications'],['Reserved Assets',assets,'Registry records']],table:'projects'},
'Registry & Rights':{metrics:[['Assets',assets,'All registry records'],['Approved Assets',approved,'Approved status'],['Indexes',indexes,'20-position diversified portfolios'],['Position size','5%','Equal Index position']],table:'asset_registry'},
'Finance':{metrics:[['Gross revenue',money(gross),'Recorded entries'],['Net distributable',money(net),'After recorded deductions'],['Outstanding allocations',money(payable),'Not marked paid'],['Revenue entries',(rev||[]).length,'Ledger rows']],table:'asset_revenue_entries'},
'Content & Marketing':{metrics:[['Campaigns',campaigns,'All campaigns'],['Approved Assets',approved,'Available source pool'],['Assets',assets,'Registry records'],['Projects',projects,'Commissioning pipeline']],table:'marketing_campaigns'},
'Support':{metrics:[['Support requests',tickets,'All requests'],['Open requests',openTickets,'Open status'],['Creators',creators,'Potential creator users'],['Notifications',notifications,'Recorded notifications']],table:'support_requests'},
'Technology':{metrics:[['Database-backed modules','Live','No synthetic KPI values'],['Assets',assets,'Registry query health'],['Projects',projects,'Project query health'],['Indexes',indexes,'Index query health']],table:'admin_audit_logs'}};
for(const key of Object.keys(map)){map[key].bars=await months(s,map[key].table);map[key].breakdown=await statuses(s,map[key].table).catch(()=>[])}return NextResponse.json({departments:map,generated_at:new Date().toISOString(),source:'Supabase live data'})}catch(e:any){return NextResponse.json({error:e.message||'Analytics unavailable'},{status:500})}}
