'use client';
import {useMemo,useState} from 'react';
import {ArrowUpRight,Globe,Music,TrendingUp,Users} from '@/components/icons';
type Department='Company overview'|'Executive'|'Creator Success'|'Projects'|'Registry & Rights'|'Finance'|'Content & Marketing'|'Support'|'Technology';
const departments:Department[]=['Company overview','Executive','Creator Success','Projects','Registry & Rights','Finance','Content & Marketing','Support','Technology'];
const data:Record<Department,{metrics:[string,string,string][];bars:number[];title:string;rank:[string,string][];secondary:[string,string][]}>={
 'Company overview':{metrics:[['Revenue growth','+18.4%','Quarter over quarter'],['Creator growth','+10.8%','18 verified this month'],['Asset utilisation','47.7%','203 of 426 in active use'],['Audience markets','24','Countries with engagement']],bars:[72,88,64,95,78,86,91,83,97,89,94,100],title:'Operating growth',rank:[['Narrative music','84%'],['Reflection & wellbeing','72%'],['Podcast experiences','61%'],['Video collections','48%']],secondary:[['Nigeria','96'],['United Kingdom','41'],['Ghana','18'],['United States','12']]},
 'Executive':{metrics:[['Operating revenue','$482,640','Current quarter'],['Net margin','31.8%','After creator PPR'],['Active projects','12','Across departments'],['Strategic risks','3','Require leadership review']],bars:[65,70,72,74,81,79,88,90,87,94,98,100],title:'Executive performance index',rank:[['Revenue plan','91%'],['Project delivery','84%'],['Creator network','76%'],['Product readiness','63%']],secondary:[['On track','17'],['Needs review','4'],['At risk','3'],['Blocked','1']]},
 'Creator Success':{metrics:[['Verified creators','184','+18 this month'],['Applications','67','Awaiting review'],['Acceptance rate','38.2%','Last 90 days'],['Creator satisfaction','4.7/5','Post-support survey']],bars:[48,55,59,63,68,72,76,83,86,90,95,100],title:'Creator network growth',rank:[['Application review','93%'],['Contract completion','81%'],['Profile completion','76%'],['Response SLA','69%']],secondary:[['Nigeria','96'],['United Kingdom','41'],['Ghana','18'],['Other','29']]},
 'Projects':{metrics:[['Active projects','12','7 in production'],['On-time rate','82%','Rolling 90 days'],['Open milestones','46','Across portfolio'],['Budget variance','+3.1%','Against approved budgets']],bars:[76,83,69,91,88,79,93,86,90,95,92,100],title:'Project delivery index',rank:[['In production','7'],['In review','3'],['At risk','2'],['Completed','36']],secondary:[['Music','8'],['Film','2'],['Podcast','1'],['Mixed media','1']]},
 'Registry & Rights':{metrics:[['Registered assets','426','Across all formats'],['Approved assets','203','Eligible for experiences'],['Rights review','31','Awaiting clearance'],['Split integrity','100%','Validated records']],bars:[62,67,73,71,78,82,84,88,91,93,97,100],title:'Registry throughput',rank:[['Audio masters','47%'],['Compositions','23%'],['Video','14%'],['Other','16%']],secondary:[['Approved','203'],['Active','116'],['Rights review','31'],['Draft','76']]},
 'Finance':{metrics:[['Gross revenue','$482,640','Current quarter'],['Creator pool','$144,792','Calculated PPR'],['Net payable','$132,408','After tax and fees'],['Unpaid batches','4','Awaiting approval']],bars:[58,66,70,77,73,82,88,84,92,94,97,100],title:'Revenue performance',rank:[['DSP revenue','68%'],['Direct sales','18%'],['Licensing','9%'],['Other','5%']],secondary:[['Approved','9'],['Pending','4'],['Paid','22'],['Disputed','1']]},
 'Content & Marketing':{metrics:[['Campaign reach','1.8M','Last 30 days'],['Engagement rate','6.4%','Across channels'],['Published items','42','This quarter'],['Conversion rate','3.8%','Landing pages']],bars:[51,63,58,69,75,72,84,81,88,92,96,100],title:'Audience growth',rank:[['Instagram','82%'],['TikTok','77%'],['YouTube','64%'],['Email','49%']],secondary:[['Music','18'],['News','11'],['Product','8'],['Events','5']]},
 'Support':{metrics:[['Open tickets','28','6 high priority'],['First response','2h 14m','Average'],['Resolution rate','91%','Within SLA'],['Satisfaction','4.6/5','Last 30 days']],bars:[82,79,85,88,84,91,89,93,95,92,98,100],title:'Support performance',rank:[['Creator support','44%'],['Account access','23%'],['Payments','18%'],['Other','15%']],secondary:[['Resolved','214'],['Open','28'],['Escalated','6'],['Waiting','11']]},
 'Technology':{metrics:[['Platform uptime','99.96%','Last 30 days'],['Open incidents','2','No critical incidents'],['Deployments','18','This month'],['Security reviews','4','All passed']],bars:[91,93,92,96,95,97,96,98,99,98,100,100],title:'Platform reliability',rank:[['Admin OS','96%'],['Studio','89%'],['Corporate web','94%'],['Consumer platform','61%']],secondary:[['Healthy','14'],['Warning','2'],['Incident','0'],['Planned work','5']]}
};
export default function AnalyticsWorkspace(){const [department,setDepartment]=useState<Department>('Company overview');const d=useMemo(()=>data[department],[department]);return <><div className="page-head"><div><div className="eyebrow">Business intelligence</div><h1 className="page-title">Analytics</h1><p className="page-copy">Select a department to see the metrics, trends and operating indicators relevant to that team.</p></div><div className="page-actions"><label className="analytics-filter"><span>Department</span><select value={department} onChange={e=>setDepartment(e.target.value as Department)}>{departments.map(x=><option key={x}>{x}</option>)}</select></label><button className="button primary">Create report <ArrowUpRight size={15}/></button></div></div><div className="analytics-context"><strong>{department}</strong><span>Department analytics view</span></div><div className="analytics-metrics">{d.metrics.map(([name,value,note],i)=>{const Icon=[TrendingUp,Users,Music,Globe][i];return <div key={name}><span><Icon/>{name}</span><strong>{value}</strong><small>{note}</small></div>})}</div><div className="dashboard-grid"><section className="card chart-card"><div className="card-head"><div><div className="card-title">{d.title}</div><p>Indexed activity across the last 12 months.</p></div><span className="status good">Current</span></div><div className="bar-chart">{d.bars.map((v,i)=><div key={i}><b style={{height:`${v}%`}}/><span>{['A','S','O','N','D','J','F','M','A','M','J','J'][i]}</span></div>)}</div></section><section className="card"><div className="card-head"><div><div className="card-title">Department distribution</div><p>Current operating position.</p></div></div><div className="donut-wrap"><div className="donut"><span><strong>{d.rank[0][1]}</strong><small>Leading measure</small></span></div><div className="legend">{d.rank.map(([n,v])=><div key={n}><i/>{n}<strong>{v}</strong></div>)}</div></div></section></div><div className="dashboard-grid lower"><section className="card"><div className="card-head"><div><div className="card-title">Performance breakdown</div><p>Key areas within {department.toLowerCase()}.</p></div></div><div className="rank-list">{d.rank.map(([n,v])=><div key={n}><span>{n}</span><i><b style={{width:v.includes('%')?v:'70%'}}/></i><strong>{v}</strong></div>)}</div></section><section className="card"><div className="card-head"><div><div className="card-title">Operational snapshot</div><p>Current department records.</p></div></div><div className="country-list">{d.secondary.map(([n,v])=><div key={n}><span>{n}</span><strong>{v}</strong></div>)}</div></section></div></>}
