'use client';
import { useEffect, useMemo, useState } from 'react';
import { Check, ChevronRight, RefreshCw, X } from 'lucide-react';

type Row = Record<string, any>;
const labels: Record<string,string>={pending:'Pending review',under_review:'Under review',shortlisted:'Shortlisted',accepted:'Accepted',rejected:'Rejected',withdrawn:'Withdrawn'};

export default function ApplicationsWorkspace(){
 const [items,setItems]=useState<Row[]>([]); const [selected,setSelected]=useState<Row|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/applications',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not load applications.');setItems(j.applications||[])}catch(e){setError(e instanceof Error?e.message:'Could not load applications.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const counts=useMemo(()=>({total:items.length,pending:items.filter(x=>['pending','under_review'].includes(x.status)).length,shortlisted:items.filter(x=>x.status==='shortlisted').length,accepted:items.filter(x=>x.status==='accepted').length}),[items]);
 const update=async(status:string)=>{if(!selected)return;setSaving(true);setError('');try{const r=await fetch('/api/applications',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected.id,status})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not update application.');const next={...selected,...j.application,status};setSelected(next);setItems(xs=>xs.map(x=>x.id===next.id?next:x))}catch(e){setError(e instanceof Error?e.message:'Could not update application.')}finally{setSaving(false)}};
 const creatorName=(x:Row)=>x.creator?.stage_name||x.creator?.legal_name||x.creator?.full_name||x.creator?.email||x.creator_user_id||'Unknown creator';
 const projectName=(x:Row)=>x.project?.title||x.project?.name||'Unknown project';
 return <><div className="page-head"><div><div className="eyebrow">Creator operations</div><h1 className="page-title">Applications</h1><p className="page-copy">Review and decide creator applications submitted through Plekxa Studio.</p></div><button className="button secondary" onClick={load}><RefreshCw size={16}/>Refresh</button></div>
 {error&&<div className="integration-banner pending"><div><strong>Database error</strong><span>{error}</span></div></div>}
 <div className="metric-grid"><article className="metric"><span>Total</span><strong>{counts.total}</strong></article><article className="metric"><span>Awaiting review</span><strong>{counts.pending}</strong></article><article className="metric"><span>Shortlisted</span><strong>{counts.shortlisted}</strong></article><article className="metric"><span>Accepted</span><strong>{counts.accepted}</strong></article></div>
 <div className="workspace-card"><div className="table-wrap"><table className="data-table"><thead><tr><th>Creator</th><th>Project</th><th>Submitted</th><th>Status</th><th/></tr></thead><tbody>{loading?<tr><td colSpan={5}>Loading applications…</td></tr>:items.length===0?<tr><td colSpan={5}>No applications found in the shared database.</td></tr>:items.map(x=><tr key={x.id} className="click-row" onClick={()=>setSelected(x)}><td><strong>{creatorName(x)}</strong><small className="table-sub">{x.creator?.email||''}</small></td><td>{projectName(x)}</td><td>{x.applied_at?new Date(x.applied_at).toLocaleDateString('en-GB'):'—'}</td><td><span className={`status ${x.status==='accepted'?'good':'warn'}`}>{labels[x.status]||x.status}</span></td><td><ChevronRight size={16}/></td></tr>)}</tbody></table></div></div>
 {selected&&<div className="drawer-backdrop" onMouseDown={()=>setSelected(null)}><aside className="record-drawer" onMouseDown={e=>e.stopPropagation()}><header className="drawer-head"><div><div className="eyebrow">Application</div><h2>{creatorName(selected)}</h2><p>{projectName(selected)}</p></div></header><div className="drawer-body"><div className="detail-grid"><div className="detail"><span>Status</span><strong>{labels[selected.status]||selected.status}</strong></div><div className="detail"><span>Portfolio</span><strong>{selected.portfolio_url?<a href={selected.portfolio_url} target="_blank">Open portfolio</a>:'Not supplied'}</strong></div></div><h3>Cover letter</h3><p>{selected.cover_letter||'No cover letter supplied.'}</p></div><footer className="drawer-actions"><button disabled={saving} className="button secondary" onClick={()=>update('rejected')}><X size={16}/>Reject</button><button disabled={saving} className="button secondary" onClick={()=>update('shortlisted')}>Shortlist</button><button disabled={saving} className="button primary" onClick={()=>update('accepted')}><Check size={16}/>Accept</button></footer></aside></div>}</>;
}
