'use client';
import { useEffect, useMemo, useState } from 'react';

type Row = Record<string, any>;
const labels: Record<string,string>={pending:'Pending review',under_review:'Under review',shortlisted:'Shortlisted',accepted:'Accepted',rejected:'Rejected',withdrawn:'Withdrawn'};

export default function ApplicationsWorkspace(){
 const [items,setItems]=useState<Row[]>([]); const [selected,setSelected]=useState<Row|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [saving,setSaving]=useState(false); const [reason,setReason]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/applications',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not load applications.');setItems(j.applications||[])}catch(e){setError(e instanceof Error?e.message:'Could not load applications.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const counts=useMemo(()=>({total:items.length,pending:items.filter(x=>['pending','under_review'].includes(x.status)).length,shortlisted:items.filter(x=>x.status==='shortlisted').length,accepted:items.filter(x=>x.status==='accepted').length}),[items]);
 const update=async(status:string)=>{if(!selected)return;if(status==='rejected'&&!reason.trim()){setError('Add a rejection reason so the creator understands the decision.');return;}setSaving(true);setError('');setNotice('');try{const r=await fetch('/api/applications',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected.id,status,rejectionReason:status==='rejected'?reason:null,reviewNotes:reason||null})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not update application.');const next={...selected,...j.application,status};setSelected(next);setItems(xs=>xs.map(x=>x.id===next.id?next:x));setNotice(j.delivery?.emailed?'Status updated and email sent.':j.delivery?.notified?'Status updated and in-app notification sent.':'Status updated. Email was not sent; check SMTP settings.')}catch(e){setError(e instanceof Error?e.message:'Could not update application.')}finally{setSaving(false)}};
 const creatorName=(x:Row)=>x.creator?.stage_name||x.creator?.legal_name||x.creator?.full_name||x.creator?.email||x.applicant_name||x.creator_user_id||'Unknown creator';
 const creatorEmail=(x:Row)=>x.creator?.email||x.applicant_email||'';
 const projectName=(x:Row)=>x.project?.title||x.project?.name||'Unknown project';
 return <><div className="page-head"><div><div className="eyebrow">Creator operations</div><h1 className="page-title">Applications</h1><p className="page-copy">Review and decide creator applications submitted through Plekxa Studio.</p></div><button className="button secondary" onClick={()=>void load()} disabled={loading}>↻ Refresh</button></div>
 {error&&<div className="integration-banner pending"><div><strong>Action required</strong><span>{error}</span></div></div>}{notice&&<div className="integration-banner"><div><strong>Update complete</strong><span>{notice}</span></div></div>}
 <div className="metric-grid"><article className="metric"><span className="metric-label">Total</span><strong className="metric-value">{counts.total}</strong></article><article className="metric"><span className="metric-label">Awaiting review</span><strong className="metric-value">{counts.pending}</strong></article><article className="metric"><span className="metric-label">Shortlisted</span><strong className="metric-value">{counts.shortlisted}</strong></article><article className="metric"><span className="metric-label">Accepted</span><strong className="metric-value">{counts.accepted}</strong></article></div>
 <div className="workspace-card"><div className="table-wrap"><table className="data-table"><thead><tr><th>Creator</th><th>Project</th><th>Submitted</th><th>Status</th><th/></tr></thead><tbody>{loading?<tr><td colSpan={5}>Loading applications…</td></tr>:items.length===0?<tr><td colSpan={5}>No applications found in the shared database.</td></tr>:items.map(x=><tr key={x.id} className="click-row" onClick={()=>{setSelected(x);setReason(x.rejection_reason||'')}}><td><strong>{creatorName(x)}</strong><small className="table-sub">{creatorEmail(x)}</small></td><td>{projectName(x)}</td><td>{x.applied_at?new Date(x.applied_at).toLocaleDateString('en-GB'):'—'}</td><td><span className={`status ${x.status==='accepted'?'good':'warn'}`}>{labels[x.status]||x.status}</span></td><td>›</td></tr>)}</tbody></table></div></div>
 {selected&&<div className="drawer-backdrop" onMouseDown={()=>setSelected(null)}><aside className="record-drawer" onMouseDown={e=>e.stopPropagation()}><header className="drawer-head"><div><div className="eyebrow">Application</div><h2>{creatorName(selected)}</h2><p>{projectName(selected)}</p><small>{creatorEmail(selected)||'No email available'}</small></div></header><div className="drawer-body"><div className="detail-grid"><div className="detail"><span>Status</span><strong>{labels[selected.status]||selected.status}</strong></div><div className="detail"><span>Portfolio</span><strong>{selected.portfolio_url?<a href={selected.portfolio_url} target="_blank" rel="noreferrer">Open portfolio</a>:'Not supplied'}</strong></div></div><h3>Cover letter</h3><p>{selected.cover_letter||'No cover letter supplied.'}</p>{selected.status==='accepted'&&<><h3>Project milestones</h3><div className="workspace-card">{(selected.milestones||[]).length?(selected.milestones||[]).map((m:Row)=><div className="picker-row" key={m.id}><div><strong>{m.title}</strong><small className="table-sub">{m.description||'No description'} · Due {m.due_at?new Date(m.due_at).toLocaleDateString('en-GB'):'not set'}</small></div><span className="status warn">{m.status}</span></div>):<p>No milestones have been created for this project.</p>}</div><h3>Uploaded deliverables</h3><div className="workspace-card">{(selected.deliverables||[]).length?(selected.deliverables||[]).map((d:Row)=><div key={d.id} style={{marginBottom:16}}><div className="picker-row"><div><strong>{d.title}</strong><small className="table-sub">{d.deliverable_type||'Deliverable'} · {d.status}</small></div><span>{(d.files||[]).length} file(s)</span></div>{(d.files||[]).map((f:Row)=><div className="picker-row" key={f.id}><div><strong>{f.file_name}</strong><small className="table-sub">Version {f.version||1} · {f.mime_type||'file'} · {f.created_at?new Date(f.created_at).toLocaleString('en-GB'):''}</small></div><a className="button secondary" href={f.public_url||f.storage_url||'#'} target="_blank" rel="noreferrer">Open</a></div>)}</div>):<p>No deliverables have been uploaded for this creator.</p>}</div></>}<label><span>Decision note / rejection reason</span><textarea rows={4} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain the decision. Rejection requires a reason."/></label></div><footer className="drawer-actions"><button disabled={saving} className="button secondary" onClick={()=>void update('rejected')}>× Reject</button><button disabled={saving} className="button secondary" onClick={()=>void update('shortlisted')}>Shortlist</button><button disabled={saving} className="button primary" onClick={()=>void update('accepted')}>✓ Accept</button></footer></aside></div>}</>;
}
