'use client';

import {useEffect,useState} from 'react';
import {Check,Plus,X} from '@/components/icons';

type Contributor={name:string;email:string;role:string;ownership_percentage:number;royalty_percentage:number};
type Asset=Record<string,any>;
const roles=['Lead creator','Supporting creator','Producer','Sponsor','Instrumentalist','Songwriter','AI prompter','Engineer','Director','Other'];
const emptyContributor=():Contributor=>({name:'',email:'',role:'Supporting creator',ownership_percentage:0,royalty_percentage:0});
const emptyAsset=():Asset=>({title:'',description:'',asset_type:'audio',isrc:'',upc:'',iswc:'',other_identifiers:'',internal_identifier:'',release_date:'',rights_start:'',rights_end:'',artwork_url:'',contract_confirmed:false,master_owner:'',status:'draft',restrictions:'',contributors:[emptyContributor()]});

export default function AssetRegistryWorkspace(){
 const[rows,setRows]=useState<Asset[]>([]);const[draft,setDraft]=useState<Asset|null>(null);const[error,setError]=useState('');const[saving,setSaving]=useState(false);const[files,setFiles]=useState<any[]>([]);const[pendingFiles,setPendingFiles]=useState<File[]>([]);const[uploading,setUploading]=useState(false);
 const load=async()=>{const r=await fetch('/api/live/assets',{cache:'no-store'});const j=await r.json();if(!r.ok)return setError(j.error||'Could not load assets.');setRows(j.records||[])};
 useEffect(()=>{void load()},[]);
 const loadFiles=async(id:string)=>{const r=await fetch(`/api/assets/files?asset_id=${id}`,{cache:'no-store'});const j=await r.json();if(r.ok)setFiles(j.files||[])};
 const categoryFor=(file:File)=>file.type.startsWith('audio/')?'audio':file.type.startsWith('video/')?'video':file.type.startsWith('image/')?'artwork':file.name.toLowerCase().endsWith('.zip')?'stems':file.type==='application/pdf'?'document':'other';
 const upload=async(file:File,assetId:string)=>{const f=new FormData();f.append('asset_id',assetId);f.append('category',categoryFor(file));f.append('file',file);const r=await fetch('/api/assets/files',{method:'POST',body:f});const j=await r.json();if(!r.ok)throw new Error(j.error||`Upload failed for ${file.name}.`);};
 const removeFile=async(id:string)=>{const r=await fetch('/api/assets/files',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const j=await r.json();if(!r.ok)return setError(j.error||'Could not remove file.');if(draft?.id)await loadFiles(draft.id)};
 const updateContributor=(index:number,patch:Partial<Contributor>)=>setDraft(d=>d?{...d,contributors:(d.contributors||[]).map((c:Contributor,i:number)=>i===index?{...c,...patch}:c)}:d);
 const save=async()=>{if(!draft?.title?.trim())return setError('Asset title is required.');const contributors=(draft.contributors||[]).filter((c:Contributor)=>c.name.trim()||c.email.trim()||Number(c.ownership_percentage)>0);const total=contributors.reduce((sum:number,c:Contributor)=>sum+Number(c.ownership_percentage||0),0);if(contributors.length&&Math.abs(total-100)>0.01)return setError(`When contributors are added, ownership must total 100%. Current total: ${total}%.`);setSaving(true);setUploading(pendingFiles.length>0);setError('');try{const method=draft.id?'PATCH':'POST';const r=await fetch('/api/live/assets',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify({...draft,contributors})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not save asset.');const assetId=String(j.record?.id||draft.id||'');if(pendingFiles.length&&assetId){for(const file of pendingFiles)await upload(file,assetId);}setPendingFiles([]);setFiles([]);setDraft(null);await load()}catch(e){setError(e instanceof Error?e.message:'Could not save asset.')}finally{setSaving(false);setUploading(false)}};
 const remove=async(row:Asset)=>{if(!confirm(`Delete “${row.title}”? This cannot be undone.`))return;const r=await fetch('/api/live/assets',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:row.id})});const j=await r.json();if(!r.ok)return setError(j.error||'Could not delete asset.');await load()};
 return <><div className="page-head"><div><div className="eyebrow">Rights & registry</div><h1 className="page-title">Asset registry</h1><p className="page-copy">Register identifiers, rights, contracts and contributor ownership for each asset.</p></div><button className="button primary" onClick={()=>{setPendingFiles([]);setFiles([]);setDraft(emptyAsset())}}><Plus size={15}/>Register asset</button></div>{error&&<div className="integration-banner pending"><div><strong>Action required</strong><span>{error}</span></div></div>}<div className="workspace-card"><div className="table-wrap"><table className="data-table"><thead><tr><th>Asset</th><th>Identifiers</th><th>Contributors</th><th>Release</th><th>Status</th><th></th></tr></thead><tbody>{rows.length?rows.map(row=><tr key={row.id}><td><strong>{row.title}</strong><small className="table-sub">{row.asset_type} · {row.description||'No description'}</small></td><td>{row.isrc||row.upc||row.internal_identifier||'—'}</td><td>{Array.isArray(row.contributors)?row.contributors.length:0}</td><td>{row.release_date||'—'}</td><td><span className="status good">{row.status}</span></td><td><button className="button secondary" onClick={()=>{setPendingFiles([]);setDraft({...row,contributors:Array.isArray(row.contributors)&&row.contributors.length?row.contributors:[emptyContributor()]});void loadFiles(row.id)}}>Edit</button> <button className="button secondary" onClick={()=>void remove(row)}>Delete</button></td></tr>):<tr><td colSpan={6}>No assets registered.</td></tr>}</tbody></table></div></div>{draft&&<div className="drawer-backdrop" onMouseDown={()=>setDraft(null)}><aside className="record-drawer wide" onMouseDown={e=>e.stopPropagation()}><header className="drawer-head"><div><div className="eyebrow">Asset registry</div><h2>{draft.id?'Edit asset':'Register asset'}</h2></div><button className="icon-button" onClick={()=>setDraft(null)}><X size={20}/></button></header><div className="drawer-body"><div className="form-grid">
 {[["title","Asset title"],["asset_type","Asset type"],["isrc","ISRC"],["upc","UPC/EAN"],["iswc","ISWC"],["internal_identifier","Internal identifier"],["other_identifiers","Other identifiers"],["release_date","Release date"],["rights_start","Licence start date"],["rights_end","Licence end date"],["artwork_url","Artwork URL"],["master_owner","Master owner"]].map(([k,l])=><label className="field" key={k}><span>{l}</span><input type={k.includes('date')||k.startsWith('rights_')?'date':'text'} value={draft[k]||''} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}
 <label className="field" style={{gridColumn:'1 / -1'}}><span>Description</span><textarea value={draft.description||''} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label className="field"><span>Status</span><select value={draft.status||'draft'} onChange={e=>setDraft({...draft,status:e.target.value})}><option>draft</option><option>rights_review</option><option>approved</option><option>active</option><option>restricted</option></select></label><label className="field"><span>Contract confirmed</span><select value={String(Boolean(draft.contract_confirmed))} onChange={e=>setDraft({...draft,contract_confirmed:e.target.value==='true'})}><option value="false">No</option><option value="true">Yes</option></select></label><label className="field" style={{gridColumn:'1 / -1'}}><span>Restrictions / rights notes</span><textarea value={draft.restrictions||''} onChange={e=>setDraft({...draft,restrictions:e.target.value})}/></label></div>
 <div className="section-heading"><div><h2>Asset files</h2><p>Optional. Upload any audio, video, artwork, stems, contracts or supporting files. Files selected for a new asset upload automatically after you save it.</p></div></div>
 <div className="workspace-card asset-upload-box"><label className="field full"><span>Choose files</span><input type="file" multiple accept=".wav,.mp3,.flac,.aiff,.aif,.m4a,.aac,.ogg,.mp4,.mov,.mkv,.webm,.jpg,.jpeg,.png,.webp,.pdf,.doc,.docx,.txt,.csv,.zip" disabled={uploading} onChange={e=>{const picked=Array.from(e.target.files||[]);setPendingFiles(current=>[...current,...picked]);e.currentTarget.value=''}}/></label>{pendingFiles.length>0&&<div>{pendingFiles.map((file,index)=><div className="picker-row" key={`${file.name}-${index}`}><div><strong>{file.name}</strong><small className="table-sub">Queued · {categoryFor(file)} · {Math.max(1,Math.round(file.size/1024))} KB</small></div><button type="button" className="button secondary" onClick={()=>setPendingFiles(xs=>xs.filter((_,i)=>i!==index))}>Remove</button></div>)}</div>}</div>
 <div className="workspace-card uploaded-files-list">{files.length?files.map(f=><div className="picker-row" key={f.id}><div><strong>{f.file_name}</strong><small className="table-sub">{f.file_category} · {Math.round(Number(f.size_bytes||0)/1024)} KB</small></div><div><a className="button secondary" href={f.public_url} target="_blank" rel="noreferrer">Open</a> <button type="button" className="button secondary" onClick={()=>void removeFile(f.id)}>Delete</button></div></div>):<p className="empty-file-note">No files uploaded yet.</p>}</div>
 <div className="section-heading"><div><h2>Contributors</h2><p>Optional. When contributors are added, ownership must total 100%.</p></div><button className="button secondary" onClick={()=>setDraft({...draft,contributors:[...(draft.contributors||[]),emptyContributor()]})}><Plus size={15}/>Add contributor</button></div>
 {(draft.contributors||[]).map((c:Contributor,i:number)=><div className="form-grid workspace-card" key={i}><label className="field"><span>Name</span><input value={c.name} onChange={e=>updateContributor(i,{name:e.target.value})}/></label><label className="field"><span>Email / contact</span><input value={c.email} onChange={e=>updateContributor(i,{email:e.target.value})}/></label><label className="field"><span>Role</span><select value={c.role} onChange={e=>updateContributor(i,{role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><label className="field"><span>Ownership %</span><input type="number" min="0" max="100" step="0.01" value={c.ownership_percentage} onChange={e=>updateContributor(i,{ownership_percentage:Number(e.target.value)})}/></label><label className="field"><span>Royalty %</span><input type="number" min="0" max="100" step="0.01" value={c.royalty_percentage} onChange={e=>updateContributor(i,{royalty_percentage:Number(e.target.value)})}/></label><button className="button secondary" onClick={()=>setDraft({...draft,contributors:draft.contributors.filter((_:Contributor,x:number)=>x!==i)})}>Remove</button></div>)}
 </div><footer className="drawer-actions"><button className="button secondary" onClick={()=>setDraft(null)}>Cancel</button><button className="button primary" disabled={saving} onClick={()=>void save()}><Check size={15}/>{saving?'Saving…':'Save asset'}</button></footer></aside></div>}</>;
}
