'use client';

import {useEffect,useState} from 'react';
import {Check,Plus,X} from '@/components/icons';
import {uploadFileToR2} from '@/lib/browser-r2';

type Contributor={name:string;email:string;role:string;ownership_percentage:number;royalty_percentage:number};
type Asset=Record<string,any>;
const roles=['Lead creator','Supporting creator','Producer','Sponsor','Instrumentalist','Songwriter','AI prompter','Engineer','Director','Other'];
const emptyContributor=():Contributor=>({name:'',email:'',role:'Supporting creator',ownership_percentage:0,royalty_percentage:0});
const emptyAsset=():Asset=>({title:'',description:'',asset_type:'audio',genre:'',mood:'',isrc:'',upc:'',iswc:'',other_identifiers:'',internal_identifier:'',release_date:'',rights_start:'',rights_end:'',artwork_url:'',contract_confirmed:false,master_owner:'',status:'draft',restrictions:'',contributors:[emptyContributor()]});

export default function AssetRegistryWorkspace(){
 const[rows,setRows]=useState<Asset[]>([]);const[draft,setDraft]=useState<Asset|null>(null);const[error,setError]=useState('');const[saving,setSaving]=useState(false);const[files,setFiles]=useState<any[]>([]);const[pendingFiles,setPendingFiles]=useState<File[]>([]);const[uploading,setUploading]=useState(false);const[uploadProgress,setUploadProgress]=useState<Record<string,number>>({});const[selectedFiles,setSelectedFiles]=useState<string[]>([]);const[notice,setNotice]=useState('');
 const load=async()=>{const r=await fetch('/api/live/assets',{cache:'no-store'});const j=await r.json();if(!r.ok)return setError(j.error||'Could not load assets.');setRows(j.records||[])};
 useEffect(()=>{void load()},[]);
 const loadFiles=async(id:string)=>{const r=await fetch(`/api/assets/files?asset_id=${id}`,{cache:'no-store'});const j=await r.json();if(r.ok)setFiles(j.files||[])};
 const categoryFor=(file:File)=>file.type.startsWith('audio/')?'audio':file.type.startsWith('video/')?'video':file.type.startsWith('image/')?'artwork':/\.(zip|rar|7z)$/i.test(file.name)?'stems':/\.(txt|pdf|lrc|docx?)$/i.test(file.name)?'document':'other';
 const upload=async(file:File,assetId:string,index:number)=>{const key=`${file.name}-${index}`;setUploadProgress(x=>({...x,[key]:0}));return uploadFileToR2('/api/assets/files',{asset_id:assetId,category:categoryFor(file)},file,p=>setUploadProgress(x=>({...x,[key]:p})));};
 const removeFile=async(id:string)=>{const r=await fetch('/api/assets/files',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const j=await r.json();if(!r.ok)return setError(j.error||'Could not remove file.');if(draft?.id)await loadFiles(draft.id)};
 const removeSelected=async()=>{if(!selectedFiles.length||!confirm(`Delete ${selectedFiles.length} selected file(s)? This removes them from Cloudflare R2 too.`))return;const r=await fetch('/api/assets/files',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:selectedFiles})});const j=await r.json();if(!r.ok)return setError(j.error||'Could not remove selected files.');setSelectedFiles([]);if(draft?.id)await loadFiles(draft.id)};

 const updateContributor=(index:number,patch:Partial<Contributor>)=>setDraft(d=>d?{...d,contributors:(d.contributors||[]).map((c:Contributor,i:number)=>i===index?{...c,...patch}:c)}:d);
 const save=async()=>{if(!draft?.title?.trim())return setError('Asset title is required.');const contributors=(draft.contributors||[]).filter((c:Contributor)=>c.name.trim()||c.email.trim()||Number(c.ownership_percentage)>0);const total=contributors.reduce((sum:number,c:Contributor)=>sum+Number(c.ownership_percentage||0),0);if(contributors.length&&Math.abs(total-100)>0.01)return setError(`When contributors are added, ownership must total 100%. Current total: ${total}%.`);setSaving(true);setUploading(pendingFiles.length>0);setError('');try{const method=draft.id?'PATCH':'POST';const r=await fetch('/api/live/assets',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify({...draft,contributors})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not save asset.');const assetId=String(j.record?.id||draft.id||'');if(pendingFiles.length&&assetId){for(const [index,file] of pendingFiles.entries())await upload(file,assetId,index);}const saved={...draft,...(j.record||{})};if(assetId&&!saved.index_id&&saved.genre&&saved.mood){const ar=await fetch('/api/indexes/assign',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({assignments:[{asset_id:assetId,genre:saved.genre,mood:saved.mood}]})});if(!ar.ok){const aj=await ar.json();throw new Error(aj.error||'Could not assign legacy Asset to a diversified Index.')}}setPendingFiles([]);setUploadProgress({});setSelectedFiles([]);setFiles([]);setDraft(null);await load()}catch(e){setError(e instanceof Error?e.message:'Could not save asset.')}finally{setSaving(false);setUploading(false)}};
 const remove=async(row:Asset)=>{if(!confirm(`Delete “${row.title}”? This cannot be undone.`))return;const r=await fetch('/api/live/assets',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:row.id})});const j=await r.json();if(!r.ok)return setError(j.error||'Could not delete asset.');await load()};
 return <><div className="page-head"><div><div className="eyebrow">Rights & registry</div><h1 className="page-title">Asset registry</h1><p className="page-copy">Manage reserved and legacy Assets, rights, contributors and authoritative files. New commissioned Assets are reserved automatically when their Project is created.</p></div><button className="button primary" onClick={()=>{setPendingFiles([]);setFiles([]);setDraft(emptyAsset())}}><Plus size={15}/>Register legacy asset</button></div>{error&&<div className="integration-banner pending"><div><strong>Action required</strong><span>{error}</span></div></div>}{notice&&<div className="integration-banner"><div><strong>Completed</strong><span>{notice}</span></div></div>}<div className="workspace-card"><div className="table-wrap"><table className="data-table"><thead><tr><th>Asset</th><th>Identifiers</th><th>Index</th><th>Contributors</th><th>Release</th><th>Status</th><th></th></tr></thead><tbody>{rows.length?rows.map(row=><tr key={row.id}><td><strong>{row.title}</strong><small className="table-sub">{row.asset_type} · {row.description||'No description'}</small></td><td>{row.isrc||row.upc||row.internal_identifier||'—'}</td><td>{row.index_id?<><span className="status good">Assigned</span><small className="table-sub">{row.genre||'No genre'} · {row.mood||'No mood'} · {Number(row.index_participation_percentage||0)}%</small></>:<span className="status">Legacy · set genre/mood</span>}</td><td>{Array.isArray(row.contributors)?row.contributors.length:0}</td><td>{row.release_date||'—'}</td><td><span className="status good">{row.status}</span></td><td><button className="button secondary" onClick={()=>{setPendingFiles([]);setDraft({...row,contributors:Array.isArray(row.contributors)&&row.contributors.length?row.contributors:[emptyContributor()]});void loadFiles(row.id)}}>Edit</button> <button className="button secondary" onClick={()=>void remove(row)}>Delete</button></td></tr>):<tr><td colSpan={7}>No assets registered.</td></tr>}</tbody></table></div></div>{draft&&<div className="drawer-backdrop" onMouseDown={()=>setDraft(null)}><aside className="record-drawer wide" onMouseDown={e=>e.stopPropagation()}><header className="drawer-head"><div><div className="eyebrow">Asset registry</div><h2>{draft.id?'Edit asset':'Register asset'}</h2></div><button className="icon-button" onClick={()=>setDraft(null)}><X size={20}/></button></header><div className="drawer-body"><div className="form-grid">
 {[["title","Asset title"],["asset_type","Asset type"],["genre","Genre"],["mood","Mood"],["isrc","ISRC"],["upc","UPC/EAN"],["iswc","ISWC"],["internal_identifier","Internal identifier"],["other_identifiers","Other identifiers"],["release_date","Release date"],["rights_start","Licence start date"],["rights_end","Licence end date"],["master_owner","Master owner"]].map(([k,l])=><label className="field" key={k}><span>{l}</span><input type={k.includes('date')||k.startsWith('rights_')?'date':'text'} value={draft[k]||''} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}
 <label className="field"><span>Artwork upload</span><input type="file" accept="image/*" onChange={e=>{const picked=Array.from(e.target.files||[]);setPendingFiles(current=>[...current,...picked]);e.currentTarget.value=''}}/></label> <label className="field" style={{gridColumn:'1 / -1'}}><span>Description</span><textarea value={draft.description||''} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label className="field"><span>Status</span><select value={draft.status||'draft'} onChange={e=>setDraft({...draft,status:e.target.value})}><option>reserved</option><option>draft</option><option>rights_review</option><option>approved</option><option>active</option><option>restricted</option></select></label><label className="field"><span>Contract confirmed</span><select value={String(Boolean(draft.contract_confirmed))} onChange={e=>setDraft({...draft,contract_confirmed:e.target.value==='true'})}><option value="false">No</option><option value="true">Yes</option></select></label><label className="field" style={{gridColumn:'1 / -1'}}><span>Restrictions / rights notes</span><textarea value={draft.restrictions||''} onChange={e=>setDraft({...draft,restrictions:e.target.value})}/></label></div>
 <div className="section-heading"><div><h2>Asset files</h2><p>Optional. Upload any audio, video, artwork, stems, contracts or supporting files. Files selected for a new asset upload automatically after you save it.</p></div></div>
 <div className="workspace-card asset-upload-box"><label className="field full"><span>Choose files</span><input type="file" multiple accept="*/*" disabled={uploading} onChange={e=>{const picked=Array.from(e.target.files||[]);setPendingFiles(current=>[...current,...picked]);e.currentTarget.value=''}}/></label><label className="field full"><span>Choose folder</span><input type="file" multiple {...({webkitdirectory:"",directory:""} as any)} disabled={uploading} onChange={e=>{const picked=Array.from(e.target.files||[]);setPendingFiles(current=>[...current,...picked]);e.currentTarget.value=''}}/></label>{pendingFiles.length>0&&<div>{pendingFiles.map((file,index)=>{const k=`${file.name}-${index}`,pct=uploadProgress[k];return <div className="picker-row" key={k}><div style={{flex:1,minWidth:0}}><strong>{file.name}</strong><small className="table-sub">{pct===undefined?'Queued':pct>=100?'Uploaded':`Uploading · ${pct}%`} · {categoryFor(file)} · {Math.max(1,Math.round(file.size/1024))} KB</small>{pct!==undefined&&<div style={{height:7,background:'#e8e5e0',borderRadius:99,overflow:'hidden',marginTop:7}}><div style={{height:'100%',width:`${pct}%`,background:'currentColor',transition:'width .15s ease'}}/></div>}</div><button type="button" className="button secondary" disabled={uploading} onClick={()=>setPendingFiles(xs=>xs.filter((_,i)=>i!==index))}>Remove</button></div>})}</div>}</div>
 <div className="workspace-card uploaded-files-list">{files.length?<><div style={{display:'flex',gap:10,alignItems:'center',justifyContent:'space-between',flexWrap:'wrap',marginBottom:12}}><label style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" checked={selectedFiles.length===files.length&&files.length>0} onChange={e=>setSelectedFiles(e.target.checked?files.map(f=>String(f.id)):[])}/><span>Select all ({files.length})</span></label><button type="button" className="button secondary" disabled={!selectedFiles.length} onClick={()=>void removeSelected()}>Delete selected{selectedFiles.length?` (${selectedFiles.length})`:''}</button></div>{files.map(f=><div className="picker-row" key={f.id}><div style={{display:'flex',gap:10,alignItems:'center',minWidth:0}}><input type="checkbox" checked={selectedFiles.includes(String(f.id))} onChange={e=>setSelectedFiles(xs=>e.target.checked?[...xs,String(f.id)]:xs.filter(x=>x!==String(f.id)))}/><div><strong>{f.file_name}</strong><small className="table-sub">{f.file_category} · {Math.round(Number(f.size_bytes||0)/1024)} KB</small></div></div><div><a className="button secondary" href={f.download_url||f.public_url||'#'} target="_blank" rel="noreferrer">Open</a> <button type="button" className="button secondary" onClick={()=>void removeFile(f.id)}>Delete</button></div></div>)}</>:<p className="empty-file-note">No files uploaded yet.</p>}</div>
 <div className="section-heading"><div><h2>Contributors</h2><p>Optional. When contributors are added, ownership must total 100%.</p></div><button className="button secondary" onClick={()=>setDraft({...draft,contributors:[...(draft.contributors||[]),emptyContributor()]})}><Plus size={15}/>Add contributor</button></div>
 {(draft.contributors||[]).map((c:Contributor,i:number)=><div className="form-grid workspace-card" key={i}><label className="field"><span>Name</span><input value={c.name} onChange={e=>updateContributor(i,{name:e.target.value})}/></label><label className="field"><span>Email / contact</span><input value={c.email} onChange={e=>updateContributor(i,{email:e.target.value})}/></label><label className="field"><span>Role</span><select value={c.role} onChange={e=>updateContributor(i,{role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><label className="field"><span>Ownership %</span><input type="number" min="0" max="100" step="0.01" value={c.ownership_percentage} onChange={e=>updateContributor(i,{ownership_percentage:Number(e.target.value)})}/></label><label className="field"><span>Royalty %</span><input type="number" min="0" max="100" step="0.01" value={c.royalty_percentage} onChange={e=>updateContributor(i,{royalty_percentage:Number(e.target.value)})}/></label><button className="button secondary" onClick={()=>setDraft({...draft,contributors:draft.contributors.filter((_:Contributor,x:number)=>x!==i)})}>Remove</button></div>)}
 </div><footer className="drawer-actions"><button className="button secondary" onClick={()=>setDraft(null)}>Cancel</button><button className="button primary" disabled={saving} onClick={()=>void save()}><Check size={15}/>{saving?'Saving…':'Save asset'}</button></footer></aside></div>}</>;
}
