'use client';
import {useEffect,useMemo,useState} from 'react';
import {Plus,X,Check,ChevronRight,Users,Percent} from '@/components/icons';
import {ASSET_TYPES,CREATOR_ROLES,Asset,Contributor,seedAssets,seedExperiences,uid,readStore,writeStore} from '@/lib/operations';
const blankContributor=():Contributor=>({id:uid('con'),name:'',role:'Supporting Creator',ppr:0});
const blank=():Asset=>({id:uid('asset'),title:'',type:'Audio Master',releaseDate:'',theme:'',identifier:'',status:'Draft',contributors:[blankContributor()]});
export default function AssetRegistryWorkspace(){const [items,setItems]=useState<Asset[]>(seedAssets);const [draft,setDraft]=useState<Asset>(blank());const [open,setOpen]=useState(false);const [selected,setSelected]=useState<Asset|null>(null);const [experiences,setExperiences]=useState(seedExperiences);const [toast,setToast]=useState('');
 useEffect(()=>{setItems(readStore('plekxa:assets',seedAssets));setExperiences(readStore('plekxa:experiences',seedExperiences))},[]);useEffect(()=>writeStore('plekxa:assets',items),[items]);
 const total=useMemo(()=>draft.contributors.reduce((a,b)=>a+Number(b.ppr||0),0),[draft]);
 const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),2100)};const updateContributor=(id:string,patch:Partial<Contributor>)=>setDraft(d=>({...d,contributors:d.contributors.map(c=>c.id===id?{...c,...patch}:c)}));
 const save=()=>{if(!draft.title||!draft.releaseDate||draft.contributors.some(c=>!c.name)||Math.abs(total-100)>.001){notify(total!==100?'Contributor PPR must total 100%':'Complete required fields');return}setItems(x=>[draft,...x]);setOpen(false);setDraft(blank());notify('Asset registered')};
 return <>{toast&&<div className="toast"><Check size={16}/>{toast}</div>}<div className="page-head"><div><div className="eyebrow">Rights & registry</div><h1 className="page-title">Asset registry</h1><p className="page-copy">Register each creative asset, its contributors and the contributor-level split of the PPR routed from its experience.</p></div><button className="button primary" onClick={()=>setOpen(true)}><Plus size={16}/>Register asset</button></div>
 <div className="metric-grid"><article className="metric"><span>Registered assets</span><strong>{items.length}</strong><small>Master registry records</small></article><article className="metric"><span>Contributors linked</span><strong>{new Set(items.flatMap(a=>a.contributors.map(c=>c.name))).size}</strong><small>Creator profiles and parties</small></article><article className="metric"><span>Rights review</span><strong>{items.filter(a=>a.status==='Rights review').length}</strong><small>Require approval</small></article><article className="metric"><span>Split integrity</span><strong>100%</strong><small>Validation required before save</small></article></div>
 <div className="workspace-card"><div className="table-wrap"><table className="data-table"><thead><tr><th>Asset</th><th>Type</th><th>Experience uses</th><th>Contributors</th><th>Status</th><th/></tr></thead><tbody>{items.map(a=><tr key={a.id} className="click-row" onClick={()=>setSelected(a)}><td><div className="record-primary"><span className="record-avatar">{a.title.slice(0,2).toUpperCase()}</span><div><strong>{a.title}</strong><small>{a.identifier||'Identifier pending'}</small></div></div></td><td>{a.type}</td><td>{experiences.filter(e=>e.assets.some(x=>x.assetId===a.id)).map(e=>e.title).join(', ')||'Not yet used'}</td><td>{a.contributors.length}</td><td><span className="status good">{a.status}</span></td><td><ChevronRight size={17}/></td></tr>)}</tbody></table></div></div>
 {(open||selected)&&<div className="drawer-backdrop" onMouseDown={()=>{setOpen(false);setSelected(null)}}><aside className="record-drawer wide" onMouseDown={e=>e.stopPropagation()}><header className="drawer-head"><div><div className="eyebrow">{open?'New registry record':'Asset record'}</div><h2>{open?'Register asset':selected?.title}</h2></div><button className="icon-button" onClick={()=>{setOpen(false);setSelected(null)}}><X size={20}/></button></header>{open?<><div className="drawer-body"><div className="form-section"><h3>Asset details</h3><div className="form-grid"><label className="field"><span>Asset title *</span><input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="field"><span>Type *</span><select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}>{ASSET_TYPES.map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Release date *</span><input type="date" value={draft.releaseDate} onChange={e=>setDraft({...draft,releaseDate:e.target.value})}/></label><label className="field"><span>Identifier</span><input placeholder="ISRC, UPC or internal ID" value={draft.identifier} onChange={e=>setDraft({...draft,identifier:e.target.value})}/></label><label className="field"><span>Status</span><select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}><option>Draft</option><option>Rights review</option><option>Approved</option><option>Active</option><option>Restricted</option></select></label><label className="field full"><span>Theme / description *</span><textarea rows={4} value={draft.theme} onChange={e=>setDraft({...draft,theme:e.target.value})}/></label></div></div>
 <div className="route-banner"><div><span>Registry status</span><strong>{draft.status}</strong></div><p>After this asset is Approved or Active, it becomes selectable from the Experience builder. PPR is routed when an experience uses it.</p></div>
 <div className="form-section"><div className="section-heading compact"><div><h3>Contributors</h3><p>Contributor PPR must total exactly 100% of this asset’s routed share.</p></div><button className="button secondary" onClick={()=>setDraft(d=>({...d,contributors:[...d.contributors,blankContributor()]}))}><Plus size={15}/>Add contributor</button></div><div className="contributor-builder">{draft.contributors.map((c,i)=><div className="contributor-row" key={c.id}><span className="asset-number">{i+1}</span><label className="field"><span>Name *</span><input value={c.name} onChange={e=>updateContributor(c.id,{name:e.target.value})}/></label><label className="field"><span>Role *</span><select value={c.role} onChange={e=>updateContributor(c.id,{role:e.target.value})}>{CREATOR_ROLES.map(r=><option key={r}>{r}</option>)}</select></label><label className="field ppr-field"><span>% PPR *</span><input type="number" min="0" max="100" value={c.ppr} onChange={e=>updateContributor(c.id,{ppr:Number(e.target.value)})}/></label><button className="icon-button danger-icon" disabled={draft.contributors.length===1} onClick={()=>setDraft(d=>({...d,contributors:d.contributors.filter(x=>x.id!==c.id)}))}><X size={16}/></button></div>)}</div><div className={`split-total ${total===100?'valid':'invalid'}`}><span>Total contributor split</span><strong>{total.toFixed(2)}%</strong><small>{total===100?'Ready to register':`${(100-total).toFixed(2)}% remaining`}</small></div></div></div><footer className="drawer-actions"><button className="button secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button primary" onClick={save}>Register asset</button></footer></>:
 <div className="drawer-body">{selected&&<><div className="record-summary"><div><span className="format-pill">{selected.type}</span><h3>{selected.title}</h3><p>{selected.theme}</p></div><div className="ppr-big"><strong>{selected.contributors.length}</strong><span>Contributors</span></div></div><div className="detail-grid"><div className="detail"><span>Release date</span><strong>{selected.releaseDate}</strong></div><div className="detail"><span>Identifier</span><strong>{selected.identifier}</strong></div></div><h3>Contributor split</h3><div className="routing-list">{selected.contributors.map(c=><div key={c.id}><div><strong>{c.name}</strong><span>{c.role}</span></div><b>{c.ppr}% of asset PPR</b></div>)}</div></>}</div>}</aside></div>}</>}
