'use client';
import {useEffect,useMemo,useState} from 'react';
import {Archive,CalendarDays,Check,ChevronRight,Download,Grid,Kanban,LayoutList,MoreHorizontal,Plus,Search,SlidersHorizontal,X} from '@/components/icons';
import type {ModuleConfig,OSRecord} from '@/lib/module-data';
import MetricCards from './MetricCards';

const statusTone=(s:unknown)=>{const v=String(s||'');return /active|approved|published|resolved|paid|verified|completed|open/i.test(v)?'good':/pending|review|draft|waiting|scheduled|shortlisted|planning|production|development/i.test(v)?'warn':/reject|restrict|suspend|cancel|closed|failed|disabled|risk/i.test(v)?'bad':''};
const initials=(value:unknown)=>String(value||'P').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();

export default function EnterpriseModule({config}:{config:ModuleConfig}){
 const storageKey=`plekxa-os:${config.slug}`;
 const [records,setRecords]=useState<OSRecord[]>(config.records); const [query,setQuery]=useState(''); const [tab,setTab]=useState(config.tabs[0]); const [view,setView]=useState<'list'|'board'>('list'); const [selected,setSelected]=useState<number|null>(null); const [creating,setCreating]=useState(false); const [draft,setDraft]=useState<OSRecord>({}); const [toast,setToast]=useState('');
 useEffect(()=>{try{const saved=localStorage.getItem(storageKey);if(saved)setRecords(JSON.parse(saved));}catch{}},[storageKey]);
 useEffect(()=>{try{localStorage.setItem(storageKey,JSON.stringify(records));}catch{}},[records,storageKey]);
 const filtered=useMemo(()=>records.map((record,index)=>({record,index})).filter(({record})=>Object.values(record).flat().join(' ').toLowerCase().includes(query.toLowerCase())),[records,query]);
 const current=selected===null?null:records[selected];
 const notify=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(''),2200)};
 const update=(patch:OSRecord)=>{if(selected===null)return;setRecords(r=>r.map((x,i)=>i===selected?{...x,...patch}:x));notify('Record updated');};
 const create=()=>{const row:OSRecord={};config.fields.forEach((f,i)=>row[f.key]=draft[f.key]|| (f.key==='status'?config.statuses[0]:i===0?'Untitled record':'—'));setRecords(r=>[row,...r]);setCreating(false);setDraft({});notify(`${config.primaryAction} created`)};
 const exportCsv=()=>{const keys=config.columns.map(c=>c.key);const csv=[config.columns.map(c=>c.label).join(','),...records.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`plekxa-${config.slug}.csv`;a.click();URL.revokeObjectURL(a.href);notify('CSV exported');};
 return <>
 {toast&&<div className="toast"><Check size={16}/>{toast}</div>}
 <div className="page-head"><div><div className="eyebrow">{config.eyebrow}</div><h1 className="page-title">{config.title}</h1><p className="page-copy">{config.description}</p></div><div className="head-actions"><button className="button secondary" onClick={exportCsv}><Download size={15}/> Export</button><button className="button primary" onClick={()=>setCreating(true)}><Plus size={15}/> {config.primaryAction}</button></div></div>
 <MetricCards items={config.metrics}/>
 <div className="workspace-card">
  <div className="module-tabs">{config.tabs.map(x=><button key={x} onClick={()=>setTab(x)} className={tab===x?'active':''}>{x}</button>)}</div>
  <div className="module-toolbar"><div className="table-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${config.title.toLowerCase()}…`}/></div><div className="toolbar-right"><span>{filtered.length} records</span><button className="icon-button"><SlidersHorizontal size={16}/></button><div className="view-switch"><button className={view==='list'?'active':''} onClick={()=>setView('list')}><LayoutList size={15}/></button><button className={view==='board'?'active':''} onClick={()=>setView('board')}><Kanban size={15}/></button></div></div></div>
  {view==='list'?<div className="table-wrap"><table className="data-table"><thead><tr>{config.columns.map(c=><th key={c.key}>{c.label}</th>)}<th/></tr></thead><tbody>{filtered.map(({record,index})=><tr key={index} className="click-row" onClick={()=>setSelected(index)}>{config.columns.map((c,ci)=><td key={c.key}>{c.key==='status'?<span className={`status ${statusTone(record[c.key])}`}>{record[c.key]}</span>:ci===0?<div className="record-primary"><span className="record-avatar">{initials(record[c.key])}</span><strong>{record[c.key]}</strong></div>:record[c.key]}</td>)}<td><ChevronRight size={17}/></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">No records match your search.</div>}</div>:
  <div className="kanban-board">{config.statuses.slice(0,5).map(status=><div className="kanban-column" key={status}><div className="kanban-head"><span>{status}</span><b>{filtered.filter(x=>x.record.status===status).length}</b></div>{filtered.filter(x=>x.record.status===status).map(({record,index})=><button className="kanban-card" key={index} onClick={()=>setSelected(index)}><strong>{String(record[config.columns[0].key])}</strong><span>{String(record[config.columns[1]?.key]||'')}</span><small>{String(record[config.columns[2]?.key]||'')}</small></button>)}</div>)}</div>}
 </div>
 {(creating||current)&&<div className="drawer-backdrop" onMouseDown={()=>{setCreating(false);setSelected(null)}}><aside className="record-drawer" onMouseDown={e=>e.stopPropagation()}><header className="drawer-head"><div><div className="eyebrow">{creating?'New record':config.title}</div><h2>{creating?config.primaryAction:String(current?.[config.columns[0].key]||'Record')}</h2></div><button className="icon-button" onClick={()=>{setCreating(false);setSelected(null)}}><X size={20}/></button></header>
  {creating?<div className="drawer-body"><div className="form-grid">{config.fields.map(f=><label className={`field ${f.type==='textarea'?'full':''}`} key={f.key}><span>{f.label}</span>{f.type==='textarea'?<textarea rows={7} value={String(draft[f.key]||'')} onChange={e=>setDraft(d=>({...d,[f.key]:e.target.value}))}/>:f.type==='select'?<select value={String(draft[f.key]||'')} onChange={e=>setDraft(d=>({...d,[f.key]:e.target.value}))}><option value="">Select…</option>{f.options?.map(o=><option key={o}>{o}</option>)}</select>:<input type={f.type==='number'?'number':'text'} value={String(draft[f.key]||'')} onChange={e=>setDraft(d=>({...d,[f.key]:e.target.value}))}/>}</label>)}</div></div>:
  <div className="drawer-body"><div className="record-hero"><span className="record-avatar large">{initials(current?.[config.columns[0].key])}</span><div><h3>{String(current?.[config.columns[0].key]||'')}</h3><span className={`status ${statusTone(current?.status)}`}>{String(current?.status||'')}</span></div></div><div className="detail-grid">{Object.entries(current||{}).map(([key,value])=><div className="detail" key={key}><span>{key.replace(/([A-Z])/g,' $1')}</span><strong>{Array.isArray(value)?value.join(', '):String(value)}</strong></div>)}</div><label className="field"><span>Internal notes</span><textarea rows={5} placeholder="Add a private note, decision or handover detail…"/></label><div className="activity-strip"><Archive size={18}/><div><strong>Record activity</strong><span>Last updated today · Full history retained in Audit Log</span></div></div></div>}
  <footer className="drawer-actions">{creating?<><button className="button secondary" onClick={()=>setCreating(false)}>Cancel</button><button className="button primary" onClick={create}>Create record</button></>:<><button className="button secondary" onClick={()=>notify('Record archived')}><Archive size={15}/> Archive</button><select className="status-select" value={String(current?.status||'')} onChange={e=>update({status:e.target.value})}>{config.statuses.map(s=><option key={s}>{s}</option>)}</select><button className="button primary" onClick={()=>{notify('Changes saved');setSelected(null)}}>Save changes</button></>}</footer>
 </aside></div>}
 </>
}
