'use client';
import {useEffect,useMemo,useState} from 'react';
import {Plus,X,ChevronRight,Check,CalendarDays,Layers,Percent} from '@/components/icons';
import {EXPERIENCE_TYPES,Asset,Experience,seedAssets,seedExperiences,uid,readStore,writeStore} from '@/lib/operations';
const blank=():Experience=>({id:uid('exp'),title:'',type:'Music',targetAudience:'',releaseDate:'',description:'',creativeDirector:'',creatorPpr:30,status:'Draft',assets:[]});
export default function ExperienceWorkspace(){
 const [items,setItems]=useState<Experience[]>(seedExperiences);const [registry,setRegistry]=useState<Asset[]>(seedAssets);const [open,setOpen]=useState(false);const [selected,setSelected]=useState<Experience|null>(null);const [draft,setDraft]=useState<Experience>(blank());const [assetToAdd,setAssetToAdd]=useState('');const [toast,setToast]=useState('');
 useEffect(()=>{setItems(readStore('plekxa:experiences',seedExperiences));setRegistry(readStore('plekxa:assets',seedAssets))},[]);useEffect(()=>writeStore('plekxa:experiences',items),[items]);
 const registered=registry.filter(a=>['Approved','Active'].includes(a.status));const available=registered.filter(a=>!draft.assets.some(x=>x.assetId===a.id));const routed=useMemo(()=>draft.assets.length?draft.creatorPpr/draft.assets.length:0,[draft]);
 const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),2200)};
 const addAsset=()=>{const a=registry.find(x=>x.id===assetToAdd);if(!a)return;setDraft(d=>({...d,assets:[...d.assets,{id:uid('ea'),assetId:a.id,title:a.title,type:a.type}]}));setAssetToAdd('')};
 const save=()=>{if(!draft.title||!draft.targetAudience||!draft.releaseDate||!draft.description||!draft.creativeDirector||!draft.assets.length){notify('Complete all required fields and add at least one registered asset');return}setItems(x=>[draft,...x]);setOpen(false);setDraft(blank());notify('Experience created with registered assets')};
 return <>{toast&&<div className="toast"><Check size={16}/>{toast}</div>}<div className="page-head"><div><div className="eyebrow">Entertainment operations</div><h1 className="page-title">Experiences</h1><p className="page-copy">Build experiences only from assets that have passed registry approval, then allocate the creator participation pool equally across the selected assets.</p></div><button className="button primary" onClick={()=>setOpen(true)}><Plus size={16}/>Create experience</button></div>
 <div className="metric-grid"><article className="metric"><span>Total experiences</span><strong>{items.length}</strong><small>Across all formats</small></article><article className="metric"><span>Approved registry assets</span><strong>{registered.length}</strong><small>Available for experiences</small></article><article className="metric"><span>Assets routed</span><strong>{items.reduce((a,b)=>a+b.assets.length,0)}</strong><small>Linked by registry ID</small></article><article className="metric"><span>Scheduled</span><strong>{items.filter(i=>i.status==='Scheduled').length}</strong><small>Ready for release</small></article></div>
 <div className="workspace-card"><div className="section-heading"><div><h2>Experience catalogue</h2><p>Every linked asset remains traceable to its registry record.</p></div></div><div className="experience-grid">{items.map(item=><button className="experience-card" key={item.id} onClick={()=>setSelected(item)}><div className="experience-card-top"><span className="format-pill">{item.type}</span><span className="status warn">{item.status}</span></div><h3>{item.title}</h3><p>{item.description}</p><div className="experience-meta"><span><CalendarDays size={14}/>{item.releaseDate}</span><span><Layers size={14}/>{item.assets.length} registered assets</span><span><Percent size={14}/>{item.creatorPpr}% creator PPR</span></div><div className="card-footer"><span>Creative Director: {item.creativeDirector}</span><ChevronRight size={17}/></div></button>)}</div></div>
 {(open||selected)&&<div className="drawer-backdrop" onMouseDown={()=>{setOpen(false);setSelected(null)}}><aside className="record-drawer wide" onMouseDown={e=>e.stopPropagation()}><header className="drawer-head"><div><div className="eyebrow">{open?'New experience':'Experience record'}</div><h2>{open?'Create experience':selected?.title}</h2></div><button className="icon-button" onClick={()=>{setOpen(false);setSelected(null)}} suppressHydrationWarning><X size={20}/></button></header>
 {open?<><div className="drawer-body"><div className="form-section"><h3>Experience details</h3><div className="form-grid"><label className="field"><span>Title *</span><input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="field"><span>Experience type *</span><select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}>{EXPERIENCE_TYPES.map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Target audience *</span><input value={draft.targetAudience} onChange={e=>setDraft({...draft,targetAudience:e.target.value})}/></label><label className="field"><span>Release date *</span><input type="date" value={draft.releaseDate} onChange={e=>setDraft({...draft,releaseDate:e.target.value})}/></label><label className="field"><span>Creative director *</span><input value={draft.creativeDirector} onChange={e=>setDraft({...draft,creativeDirector:e.target.value})}/></label><label className="field"><span>Status</span><select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}><option>Draft</option><option>In development</option><option>In production</option><option>Scheduled</option><option>Published</option></select></label><label className="field full"><span>Description *</span><textarea rows={5} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label></div></div>
 <div className="form-section ppr-panel"><div><h3>Creator participation pool</h3><p>This percentage is divided equally across the selected registered assets. Contributor splits remain controlled inside each asset record.</p></div><label className="percentage-input"><input type="number" min="0" max="100" value={draft.creatorPpr} onChange={e=>setDraft({...draft,creatorPpr:Number(e.target.value)})}/><span>% PPR</span></label></div>
 <div className="form-section"><div className="section-heading compact"><div><h3>Registered assets</h3><p>Only Approved or Active assets can be added. Draft and rights-review records are excluded.</p></div></div><div className="registry-picker"><select value={assetToAdd} onChange={e=>setAssetToAdd(e.target.value)}><option value="">Select a registered asset</option>{available.map(a=><option key={a.id} value={a.id}>{a.title} · {a.type} · {a.identifier||'ID pending'}</option>)}</select><button className="button secondary" disabled={!assetToAdd} onClick={addAsset}><Plus size={15}/>Add selected asset</button></div>{!registered.length&&<div className="inline-warning">No assets are approved yet. Approve an asset in Asset Registry before creating an experience.</div>}<div className="asset-builder">{draft.assets.map((a,i)=><div className="asset-builder-row registered" key={a.id}><span className="asset-number">{i+1}</span><div className="registered-asset"><strong>{a.title}</strong><span>{a.type} · Registry ID: {a.assetId}</span></div><div className="route-box"><span>Routed PPR</span><strong>{routed.toFixed(2)}%</strong></div><button className="icon-button danger-icon" onClick={()=>setDraft(d=>({...d,assets:d.assets.filter(x=>x.id!==a.id)}))}><X size={16}/></button></div>)}</div></div></div><footer className="drawer-actions"><button className="button secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button primary" onClick={save}>Create experience</button></footer></>:
 <div className="drawer-body">{selected&&<><div className="record-summary"><div><span className="format-pill">{selected.type}</span><h3>{selected.title}</h3><p>{selected.description}</p></div><div className="ppr-big"><strong>{selected.creatorPpr}%</strong><span>Creator PPR</span></div></div><div className="detail-grid"><div className="detail"><span>Target audience</span><strong>{selected.targetAudience}</strong></div><div className="detail"><span>Release date</span><strong>{selected.releaseDate}</strong></div><div className="detail"><span>Creative director</span><strong>{selected.creativeDirector}</strong></div><div className="detail"><span>Status</span><strong>{selected.status}</strong></div></div><h3>Registered asset routing</h3><div className="routing-list">{selected.assets.map(a=><div key={a.id}><div><strong>{a.title}</strong><span>{a.type} · {a.assetId}</span></div><b>{(selected.creatorPpr/selected.assets.length).toFixed(2)}% of experience revenue</b></div>)}</div></>}</div>}
 </aside></div>}</>}
