"use client";
import {useEffect,useState} from "react";
import LiveModuleWorkspace from "@/components/LiveModuleWorkspace";
import {liveModules} from "@/lib/live-modules";
export default function NewsroomWorkspace(){
 const[page,setPage]=useState<any>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{fetch("/api/live/pages",{cache:"no-store"}).then(r=>r.json()).then(j=>{const x=(j.records||[]).find((r:any)=>r.slug==="newsroom");setPage(x||{title:"Newsroom",slug:"newsroom",template:"newsroom",eyebrow:"Newsroom",headline:"Ideas, progress and stories from Plekxa.",summary:"Company announcements, product updates and perspectives on entertainment and media.",status:"published"})}).catch(e=>setMessage(e.message)).finally(()=>setLoading(false))},[]);
 const save=async()=>{setSaving(true);setMessage("");try{const creating=!page?.id;const r=await fetch("/api/live/pages",{method:creating?"POST":"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(page)}),j=await r.json();if(!r.ok)throw new Error(j.error||"Could not save Newsroom page.");setPage(j.record);setMessage("Newsroom page copy saved. Public site refreshes automatically.")}catch(e){setMessage(e instanceof Error?e.message:"Could not save.")}finally{setSaving(false)}};
 return <>{!loading&&page?<div className="workspace-card" style={{padding:24,marginBottom:24}}><div className="eyebrow">Public Newsroom page</div><h2>Page heading</h2><p className="page-copy">These fields control the public /newsroom hero. Articles are managed below.</p>{message&&<div className="integration-banner pending"><span>{message}</span></div>}<div className="form-grid"><label className="field"><span>Eyebrow</span><input value={page.eyebrow||""} onChange={e=>setPage({...page,eyebrow:e.target.value})}/></label><label className="field full"><span>Headline</span><input value={page.headline||""} onChange={e=>setPage({...page,headline:e.target.value})}/></label><label className="field full"><span>Introduction</span><textarea rows={3} value={page.summary||""} onChange={e=>setPage({...page,summary:e.target.value})}/></label><label className="field"><span>Status</span><select value={page.status||"published"} onChange={e=>setPage({...page,status:e.target.value})}><option value="published">Published</option><option value="draft">Draft</option><option value="archived">Archived</option></select></label></div><button className="button primary" disabled={saving} onClick={()=>void save()}>{saving?"Saving…":"Save Newsroom page"}</button></div>:null}<LiveModuleWorkspace config={liveModules.newsroom}/></>
}
