'use client';
import {useEffect,useState} from 'react';
import {Check,Shield,Plus,X} from '@/components/icons';
import {ALL_ROUTES,DEFAULT_ROLES,MASTER_ONLY,PermissionRole,ROUTE_LABELS,permissionsFor,readRoles,writeRoles} from '@/lib/access';
import {uid,readStore,writeStore} from '@/lib/operations';
type Staff={id:string;auth_user_id?:string|null;name:string;email:string;department:string;job:string;access:string;status:'Active'|'Invited'|'Suspended';invitedAt?:string};
const seedStaff:Staff[]=[{id:'staff-1',name:'Anthony Ighomena',email:'anthony@plekxa.com',department:'Executive',job:'Chief Executive Officer',access:'Master Admin',status:'Active'}];
const emptyRole=():PermissionRole=>({id:uid('role'),name:'',description:'',permissions:['/dashboard','/profile','/search'],system:false,master:false});
export default function PeopleAccessWorkspace(){
 const[roles,setRoles]=useState<PermissionRole[]>(DEFAULT_ROLES);const[staff,setStaff]=useState<Staff[]>(seedStaff);const[selectedId,setSelectedId]=useState('staff-1');const[preview,setPreview]=useState('Master Admin');const[roleOpen,setRoleOpen]=useState(false);const[inviteOpen,setInviteOpen]=useState(false);const[editingRole,setEditingRole]=useState<PermissionRole|null>(null);const[roleDraft,setRoleDraft]=useState(emptyRole());const[invite,setInvite]=useState({name:'',email:'',department:'',job:'',access:'Viewer'});const[toast,setToast]=useState('');const[busy,setBusy]=useState(false);
 const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),3500)};
 const loadStaff=async()=>{try{const r=await fetch('/api/admin/staff',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error);const mapped:Staff[]=j.staff.map((s:any)=>({id:s.id,auth_user_id:s.auth_user_id,name:s.full_name,email:s.email,department:s.department||'',job:s.job_title||'',access:s.role_name||'Viewer',status:s.status,invitedAt:s.invited_at}));setStaff(mapped);if(mapped.length&&!mapped.some(x=>x.id===selectedId))setSelectedId(mapped[0].id)}catch{setStaff(readStore('plekxa:staff',seedStaff))}};
 useEffect(()=>{setRoles(readRoles());loadStaff();const r=localStorage.getItem('plekxa:current-role');if(r)setPreview(r)},[]);useEffect(()=>writeStore('plekxa:staff',staff),[staff]);
 const selected=staff.find(s=>s.id===selectedId)||staff[0];const selectedRole=roles.find(r=>r.name===selected?.access);
 const previewRole=(name:string)=>{setPreview(name);localStorage.setItem('plekxa:current-role',name);window.dispatchEvent(new Event('plekxa-role-change'));notify(`Previewing ${name} access`)};
 const saveRole=()=>{if(!roleDraft.name.trim())return notify('Enter a role name');if(roles.some(r=>r.name.toLowerCase()===roleDraft.name.toLowerCase()&&r.id!==roleDraft.id))return notify('A role with this name already exists');const next=editingRole?roles.map(r=>r.id===roleDraft.id?roleDraft:r):[...roles,roleDraft];setRoles(next);writeRoles(next);setRoleOpen(false);setEditingRole(null);setRoleDraft(emptyRole());notify(editingRole?'Role updated':'Role created')};
 const openEdit=(r:PermissionRole)=>{setEditingRole(r);setRoleDraft({...r,permissions:[...r.permissions]});setRoleOpen(true)};const togglePermission=(route:string)=>setRoleDraft(d=>({...d,permissions:d.permissions.includes(route)?d.permissions.filter(p=>p!==route):[...d.permissions,route]}));
 const sendInvite=async()=>{if(!invite.email||!invite.name)return notify('Name and email are required');setBusy(true);try{const r=await fetch('/api/admin/invites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(invite)});const j=await r.json();if(!r.ok)throw new Error(j.error);await loadStaff();setInviteOpen(false);setInvite({name:'',email:'',department:'',job:'',access:'Viewer'});notify('Invitation email sent and employee added as Invited')}catch(e){await loadStaff();notify(e instanceof Error?e.message:'Invitation failed')}finally{setBusy(false)}};
 const changeMemberRole=async(access:string)=>{if(!selected)return;setStaff(x=>x.map(s=>s.id===selected.id?{...s,access}:s));const r=await fetch('/api/admin/staff',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected.id,role_name:access})});if(!r.ok)notify('Role changed locally, but database update failed');else notify('Employee permissions updated')};
 const removeMember=async(permanent=false)=>{if(!selected||selected.access==='Master Admin')return notify('Master Admin cannot be removed here');if(!confirm(permanent?'Permanently delete this employee and their login?':'Suspend this employee’s access?'))return;const r=await fetch('/api/admin/staff',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected.id,auth_user_id:selected.auth_user_id,permanent})});const j=await r.json();if(!r.ok)return notify(j.error||'Action failed');await loadStaff();notify(permanent?'Employee deleted':'Employee access suspended')};
 return <>{toast&&<div className="toast"><Check size={16}/>{toast}</div>}<div className="page-head"><div><div className="eyebrow">Company management</div><h1 className="page-title">People, roles and access</h1><p className="page-copy">Invite employees, create roles, edit permissions and manage staff access from one place.</p></div><div className="page-actions"><button className="button secondary" onClick={()=>{setEditingRole(null);setRoleDraft(emptyRole());setRoleOpen(true)}}><Plus size={15}/>New role</button><button className="button primary" onClick={()=>setInviteOpen(true)}><Plus size={15}/>Invite employee</button></div></div>
 <div className="access-banner"><div><Shield size={22}/><div><strong>Access preview</strong><span>Test the sidebar and direct-page guard for any role.</span></div></div><select value={preview} onChange={e=>previewRole(e.target.value)}>{roles.map(r=><option key={r.id}>{r.name}</option>)}</select></div>
 <div className="role-manager workspace-card"><div className="section-heading"><div><h2>Roles and permissions</h2><p>{roles.length} roles configured.</p></div></div><div className="role-cards">{roles.map(r=><button key={r.id} onClick={()=>openEdit(r)}><div><strong>{r.name}</strong><span>{r.description}</span></div><b>{r.permissions.length} areas</b></button>)}</div></div>
 <div className="access-layout"><div className="workspace-card"><div className="section-heading"><div><h2>Staff directory</h2><p>{staff.filter(s=>s.status==='Active').length} active · {staff.filter(s=>s.status==='Invited').length} invited</p></div></div><div className="staff-list">{staff.map(s=><button className={selected?.id===s.id?'active':''} key={s.id} onClick={()=>setSelectedId(s.id)}><span className="record-avatar">{s.name.split(' ').map(x=>x[0]).slice(0,2)}</span><div><strong>{s.name}</strong><small>{s.email}<br/>{s.job||'Role pending'} · {s.department||'Department pending'}</small></div><span className={`status ${s.status==='Active'?'good':'warn'}`}>{s.status}</span></button>)}</div></div>
 <div className="workspace-card access-detail">{selected&&<><div className="section-heading"><div><h2>{selected.name}</h2><p>{selected.email}</p></div></div><div className="detail-grid"><div className="detail"><span>Job title</span><strong>{selected.job||'Not set'}</strong></div><div className="detail"><span>Department</span><strong>{selected.department||'Not set'}</strong></div><label className="field"><span>Access role</span><select value={selected.access} disabled={selected.access==='Master Admin'} onChange={e=>changeMemberRole(e.target.value)}>{roles.map(r=><option key={r.id}>{r.name}</option>)}</select></label><div className="detail"><span>Account</span><strong>{selected.status}</strong></div></div><h3>Visible work areas</h3><div className="permission-chips">{permissionsFor(selected.access,roles).map(p=><span key={p}><Check size={13}/>{ROUTE_LABELS[p]}</span>)}</div><h3>Master controls</h3><div className="master-controls">{MASTER_ONLY.map(m=><div key={m}><span>{m}</span><strong>{selectedRole?.master?'Allowed':'Not allowed'}</strong></div>)}</div>{selected.access!=='Master Admin'&&<div className="page-actions danger-zone"><button className="button secondary" onClick={()=>removeMember(false)}>Suspend access</button><button className="button danger" onClick={()=>removeMember(true)}>Delete employee</button></div>}</>}</div></div>
 {roleOpen&&<div className="drawer-backdrop" onMouseDown={()=>setRoleOpen(false)}><aside className="record-drawer wide" onMouseDown={e=>e.stopPropagation()}><header className="drawer-head"><div><div className="eyebrow">Access control</div><h2>{editingRole?'Edit role':'Create role'}</h2></div><button className="icon-button" onClick={()=>setRoleOpen(false)}><X size={20}/></button></header><div className="drawer-body"><div className="form-grid"><label className="field"><span>Role name *</span><input disabled={roleDraft.master} value={roleDraft.name} onChange={e=>setRoleDraft({...roleDraft,name:e.target.value})}/></label><label className="field full"><span>Description</span><textarea rows={3} value={roleDraft.description} onChange={e=>setRoleDraft({...roleDraft,description:e.target.value})}/></label></div><h3>Allowed work areas</h3><div className="permission-matrix">{ALL_ROUTES.map(route=><label key={route}><input type="checkbox" disabled={roleDraft.master} checked={roleDraft.permissions.includes(route)} onChange={()=>togglePermission(route)}/><span><strong>{ROUTE_LABELS[route]}</strong><small>{route}</small></span></label>)}</div></div><footer className="drawer-actions"><button className="button secondary" onClick={()=>setRoleOpen(false)}>Cancel</button><button className="button primary" onClick={saveRole}>Save role</button></footer></aside></div>}
 {inviteOpen&&<div className="drawer-backdrop" onMouseDown={()=>setInviteOpen(false)}><aside className="record-drawer" onMouseDown={e=>e.stopPropagation()}><header className="drawer-head"><div><div className="eyebrow">Team invitation</div><h2>Invite employee</h2></div><button className="icon-button" onClick={()=>setInviteOpen(false)}><X size={20}/></button></header><div className="drawer-body"><div className="form-grid"><label className="field"><span>Full name *</span><input value={invite.name} onChange={e=>setInvite({...invite,name:e.target.value})}/></label><label className="field"><span>Email *</span><input type="email" value={invite.email} onChange={e=>setInvite({...invite,email:e.target.value})}/></label><label className="field"><span>Department</span><input value={invite.department} onChange={e=>setInvite({...invite,department:e.target.value})}/></label><label className="field"><span>Job title</span><input value={invite.job} onChange={e=>setInvite({...invite,job:e.target.value})}/></label><label className="field full"><span>Access role</span><select value={invite.access} onChange={e=>setInvite({...invite,access:e.target.value})}>{roles.filter(r=>!r.master).map(r=><option key={r.id}>{r.name}</option>)}</select></label></div></div><footer className="drawer-actions"><button className="button secondary" onClick={()=>setInviteOpen(false)}>Cancel</button><button className="button primary" disabled={busy} onClick={sendInvite}>{busy?'Sending…':'Send invitation'}</button></footer></aside></div>}</>}
