'use client';
import { useEffect, useMemo, useState } from 'react';

type Row = Record<string, any>;
const labels: Record<string,string> = { submitted:'Submitted', under_review:'Under review', approved:'Approved', held:'Held', rejected:'Rejected' };

export default function ProposalsWorkspace(){
  const [items,setItems]=useState<Row[]>([]); const [selected,setSelected]=useState<Row|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [notes,setNotes]=useState('');
  const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/proposals',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not load proposals.');setItems(j.proposals||[])}catch(e){setError(e instanceof Error?e.message:'Could not load proposals.')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const counts=useMemo(()=>({total:items.length,review:items.filter(x=>['submitted','under_review'].includes(x.status)).length,approved:items.filter(x=>x.status==='approved').length,held:items.filter(x=>x.status==='held').length}),[items]);
  const creatorName=(x:Row)=>x.creator?.stage_name||x.creator?.legal_name||x.creator?.email||'Unknown creator';
  const update=async(status:string)=>{if(!selected)return;setSaving(true);setError('');setNotice('');try{const r=await fetch('/api/proposals',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected.id,status,reviewNotes:notes})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not update proposal.');const next={...selected,...j.proposal,status};setSelected(next);setItems(xs=>xs.map(x=>x.id===next.id?next:x));setNotice(j.delivery?.emailed?'Status updated and email sent.':j.delivery?.notified?'Status updated and in-app notification sent.':'Status updated. Email was not sent; check SMTP settings.')}catch(e){setError(e instanceof Error?e.message:'Could not update proposal.')}finally{setSaving(false)}};
  return <><div className="page-head"><div><div className="eyebrow">Studio operations</div><h1 className="page-title">Proposals & pitches</h1><p className="page-copy">Review creator ideas submitted through Plekxa Studio.</p></div><button className="button secondary" onClick={()=>void load()} disabled={loading}>↻ Refresh</button></div>
  {error&&<div className="integration-banner pending"><div><strong>Database error</strong><span>{error}</span></div></div>}{notice&&<div className="integration-banner"><div><strong>Update complete</strong><span>{notice}</span></div></div>}
  <div className="metric-grid"><article className="metric"><span>Total</span><strong>{counts.total}</strong></article><article className="metric"><span>Awaiting review</span><strong>{counts.review}</strong></article><article className="metric"><span>Approved</span><strong>{counts.approved}</strong></article><article className="metric"><span>Held</span><strong>{counts.held}</strong></article></div>
  <div className="workspace-card"><div className="table-wrap"><table className="data-table"><thead><tr><th>Proposal</th><th>Creator</th><th>Department</th><th>Status</th><th/></tr></thead><tbody>{loading?<tr><td colSpan={5}>Loading proposals…</td></tr>:items.length===0?<tr><td colSpan={5}>No proposals found.</td></tr>:items.map(x=><tr key={x.id} className="click-row" onClick={()=>{setSelected(x);setNotes(x.review_notes||'')}}><td><strong>{x.title}</strong><small className="table-sub">{x.summary||''}</small></td><td>{creatorName(x)}</td><td>{x.department||'—'}</td><td><span className={`status ${x.status==='approved'?'good':'warn'}`}>{labels[x.status]||x.status}</span></td><td>›</td></tr>)}</tbody></table></div></div>
  {selected&&<div className="drawer-backdrop" onMouseDown={()=>setSelected(null)}><aside className="record-drawer" onMouseDown={e=>e.stopPropagation()}><header className="drawer-head"><div><div className="eyebrow">Proposal</div><h2>{selected.title}</h2><p>{creatorName(selected)}</p></div></header><div className="drawer-body"><h3>Summary</h3><p>{selected.summary||'No summary.'}</p><h3>Full concept</h3><p>{selected.description||'No description.'}</p><label><span>Review notes</span><textarea rows={5} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Feedback sent with the decision"/></label></div><footer className="drawer-actions"><button disabled={saving} className="button secondary" onClick={()=>void update('rejected')}>Reject</button><button disabled={saving} className="button secondary" onClick={()=>void update('held')}>Hold</button><button disabled={saving} className="button primary" onClick={()=>void update('approved')}>Approve</button></footer></aside></div>}</>;
}
