import {NextResponse} from 'next/server';
import {createClient} from '@supabase/supabase-js';
export const dynamic='force-dynamic';
type Row=Record<string,any>;
const db=()=>{const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.SUPABASE_SERVICE_ROLE_KEY;return u&&k?createClient(u,k,{auth:{persistSession:false,autoRefreshToken:false}}):null};
const msg=(e:any)=>e?.message||'Database request failed.';
const parseAssetIds=(value:unknown):string[]=>{
  if(!Array.isArray(value))return [];
  return [...new Set(value.filter((item):item is string=>typeof item==='string'&&item.trim().length>0).map(item=>item.trim()))];
};
async function syncAssets(s:any,experienceId:string,assetIds:string[],pool:number){if(assetIds.length>20)throw new Error('An experience can contain no more than 20 assets.');await s.from('experience_assets').delete().eq('experience_id',experienceId);if(assetIds.length){const share=pool/assetIds.length;const rows=assetIds.map((asset_id,position)=>({experience_id:experienceId,asset_id,position,ownership_share:share}));const {error}=await s.from('experience_assets').insert(rows);if(error)throw error;}await s.from('experiences').update({asset_count:assetIds.length,asset_share_percentage:assetIds.length?pool/assetIds.length:0,asset_ids:assetIds}).eq('id',experienceId)}
export async function GET(){try{const s=db();if(!s)return NextResponse.json({error:'Supabase service credentials are not configured.'},{status:503});const {data,error}=await s.from('experiences').select('*').order('created_at',{ascending:false});if(error)throw error;return NextResponse.json({records:data||[]})}catch(e){return NextResponse.json({error:msg(e)},{status:500})}}
export async function POST(r:Request){try{const s=db();if(!s)return NextResponse.json({error:'Supabase service credentials are not configured.'},{status:503});const b=await r.json();const assetIds=parseAssetIds(b.asset_ids);const row={title:b.title,slug:b.slug||null,description:b.description||null,target_audience:b.target_audience||null,artwork_url:b.artwork_url||null,budget:Number(b.budget||0),director:b.director||null,contributor_pool_percentage:Number(b.contributor_pool_percentage||0),published_at:b.published_at||null,status:b.status||'draft',asset_count:assetIds.length,asset_share_percentage:assetIds.length?Number(b.contributor_pool_percentage||0)/assetIds.length:0,asset_ids:assetIds};const {data,error}=await s.from('experiences').insert(row).select('*').single();if(error)throw error;await syncAssets(s,data.id,assetIds,row.contributor_pool_percentage);return NextResponse.json({record:data})}catch(e){return NextResponse.json({error:msg(e)},{status:500})}}
export async function PATCH(r:Request){try{const s=db();if(!s)return NextResponse.json({error:'Supabase service credentials are not configured.'},{status:503});const b=await r.json();if(!b.id)return NextResponse.json({error:'Experience ID is required.'},{status:400});const assetIds=parseAssetIds(b.asset_ids);const patch={title:b.title,slug:b.slug||null,description:b.description||null,target_audience:b.target_audience||null,artwork_url:b.artwork_url||null,budget:Number(b.budget||0),director:b.director||null,contributor_pool_percentage:Number(b.contributor_pool_percentage||0),published_at:b.published_at||null,status:b.status||'draft'};const {data,error}=await s.from('experiences').update(patch).eq('id',b.id).select('*').single();if(error)throw error;await syncAssets(s,b.id,assetIds,patch.contributor_pool_percentage);return NextResponse.json({record:{...data,asset_ids:assetIds}})}catch(e){return NextResponse.json({error:msg(e)},{status:500})}}
export async function DELETE(r:Request){try{const s=db();if(!s)return NextResponse.json({error:'Supabase service credentials are not configured.'},{status:503});const {id}=await r.json();await s.from('experience_assets').delete().eq('experience_id',id);const {error}=await s.from('experiences').delete().eq('id',id);if(error)throw error;return NextResponse.json({ok:true})}catch(e){return NextResponse.json({error:msg(e)},{status:500})}}
