'use client';
import{useEffect,useMemo,useState}from'react';import Link from'next/link';
const label=(v:any)=>String(v||'').toLowerCase()==='r_b'?'R&B':String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export default function Page(){const[exporting,setExporting]=useState(false),[rows,setRows]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState('all');
const load=async()=>{try{const r=await fetch('/api/indexes/detail',{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error);setRows(j.indexes||[])}catch(e){setError(e instanceof Error?e.message:'Could not load indexes')}};useEffect(()=>{void load()},[]);
const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return rows.filter(i=>{if(status!=='all'&&String(i.status)!==status)return false;if(!q)return true;const assetText=(i.assets||[]).map((a:any)=>[a.title,a.internal_identifier,a.genre,a.mood].join(' ')).join(' ');return [i.index_code,i.status,(i.genres||[]).flat().join(' '),(i.moods||[]).flat().join(' '),assetText].join(' ').toLowerCase().includes(q)})},[rows,query,status]);
const exportIt=async()=>{setExporting(true);try{const r=await fetch('/api/indexes/export');if(!r.ok)throw new Error('Export failed');const b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='Plekxa_Index_Register.xlsx';a.click();URL.revokeObjectURL(u)}catch(e){setError(e instanceof Error?e.message:'Export failed')}finally{setExporting(false)}};
return <><div className="page-head"><div><div className="eyebrow">Rights & registry</div><h1 className="page-title">Indexes</h1><p className="page-copy">20-Asset economic portfolios diversified by genre and mood. Search an Index directly or find it by an Asset inside it.</p></div><button className="button secondary" disabled={exporting} onClick={()=>void exportIt()}>{exporting?'Preparing backup…':'Export Index Register'}</button></div>{error&&<div className="integration-banner pending"><span>{error}</span></div>}
<div className="metric-grid"><article className="metric"><span>Total indexes</span><strong>{rows.length}</strong></article><article className="metric"><span>Assets reserved</span><strong>{rows.reduce((n,i)=>n+(i.assets?.length||0),0)}</strong></article><article className="metric"><span>Open capacity</span><strong>{rows.reduce((n,i)=>n+Math.max(0,20-(i.assets?.length||0)),0)}</strong></article></div>
<div className="workspace-card"><div className="module-toolbar"><div className="table-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Index ID, genre, mood, Asset title or Asset ID…"/></div><div className="toolbar-right"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{Array.from(new Set(rows.map(i=>String(i.status)).filter(Boolean))).map(s=><option key={s} value={s}>{label(s)}</option>)}</select><span>{filtered.length} indexes</span><button className="button secondary" onClick={()=>void load()}>Refresh</button></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Index</th><th>Assets reserved</th><th>Genre mix</th><th>Mood mix</th><th>Status</th></tr></thead><tbody>{filtered.length?filtered.map(i=><tr key={i.id} className="click-row" onClick={()=>setSelected(i)}><td><strong>{i.index_code}</strong></td><td>{i.assets.length}/20</td><td>{i.genres.slice(0,3).map((x:any)=>`${label(x[0])} (${x[1]})`).join(', ')||'—'}</td><td>{i.moods.slice(0,3).map((x:any)=>`${label(x[0])} (${x[1]})`).join(', ')||'—'}</td><td><span className="status good">{label(i.status)}</span></td></tr>):<tr><td colSpan={5}>No matching indexes.</td></tr>}</tbody></table></div></div>
{selected&&<div className="drawer-backdrop" onMouseDown={()=>setSelected(null)}><aside className="record-drawer wide" onMouseDown={e=>e.stopPropagation()}><header className="drawer-head"><div><div className="eyebrow">Diversified Index</div><h2>{selected.index_code}</h2></div><button className="icon-button" onClick={()=>setSelected(null)}>×</button></header><div className="drawer-body"><div className="metric-grid"><article className="metric"><span>Reserved</span><strong>{selected.assets.length}/20</strong></article><article className="metric"><span>Position</span><strong>5% each</strong></article><article className="metric"><span>Available</span><strong>{Math.max(0,20-selected.assets.length)}</strong></article></div><h3 style={{marginTop:22}}>Assets in this Index</h3><p className="page-copy">Open an Asset's originating Project workspace. Legacy Assets without a Project open in the Asset Registry.</p>{selected.assets.length?selected.assets.map((a:any)=><Link key={a.id} href={a.project_uuid?`/projects/${a.project_uuid}`:'/assets'} className="detail" style={{marginTop:8,textDecoration:'none',display:'block'}}><span>{a.internal_identifier||'Reserved Asset'} · {label(a.status)}</span><strong>{a.title}</strong><small>{label(a.genre)||'No genre'} · {label(a.mood)||'No mood'} · 5% · {a.project_uuid?'Open Project →':'Open Asset Registry →'}</small></Link>):<div className="detail" style={{marginTop:8}}>No Assets reserved in this Index yet.</div>}</div></aside></div>}</>}
