'use client';
import {useEffect,useMemo,useState} from 'react';import {useParams} from 'next/navigation';import Link from 'next/link';
const name=(c:any)=>c?.display_name||c?.stage_name||c?.legal_name||c?.email||'Creator';
export default function ProjectHub(){const params=useParams<{id:string}>(),id=String(params.id),[data,setData]=useState<any>(null),[msg,setMsg]=useState(''),[form,setForm]=useState<any>({creator_id:'',ownership_percent:0,pay_amount:0,pay_currency:'GBP',role_name:'Contributor'}),[milestone,setMilestone]=useState<any>({title:'',due_at:''}),[deliverable,setDeliverable]=useState<any>({title:'',workspace_id:'',due_at:'',deliverable_type:'creative'}),[tab,setTab]=useState('overview');
 const load=async()=>{const r=await fetch(`/api/projects/${id}/production`,{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error);setData(j)};useEffect(()=>{load().catch(e=>setMsg(e.message))},[id]);
 const call=async(action:string,extra:any={})=>{setMsg('Saving…');const r=await fetch(`/api/projects/${id}/production`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...form,...extra})}),j=await r.json();if(!r.ok){setMsg(j.error);return}setMsg('Saved.');await load()};
 const decide=async(app:any,status:string)=>{const reason=status==='rejected'?window.prompt('Rejection reason (required)')||'':'';if(status==='rejected'&&!reason)return;setMsg('Updating application…');const r=await fetch('/api/applications',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:app.id,status,rejectionReason:reason||null,reviewNotes:reason||null})});const j=await r.json();if(!r.ok){setMsg(j.error||'Could not update application.');return}setMsg('Application updated.');await load()};
 const total=useMemo(()=>data?.contributors?.reduce((n:number,x:any)=>n+Number(x.master_share||0),0)||0,[data]);if(!data)return <div>{msg||'Loading Project Hub…'}</div>;
 const director=data.creators.find((c:any)=>c.id===data.project.director_creator_id);
 return <><div className="page-head"><div><div className="eyebrow">Project Hub</div><h1 className="page-title">{data.project.title}</h1><p className="page-copy">Everything operational for this Project lives here: Director, applications, commissions, milestones, deliverables and Asset contributors.</p></div><Link className="button secondary" href="/projects">Back to Projects</Link></div>{msg&&<div className="integration-banner pending"><span>{msg}</span></div>}
 <nav aria-label="Project sections" style={{display:'flex',gap:8,overflowX:'auto',padding:'4px 0 12px',marginTop:16,borderBottom:'1px solid var(--line)'}}>
 {['overview','director','applications','contributors','milestones','deliverables','asset'].map(t=><button key={t} className={`button ${tab===t?'primary':'secondary'}`} onClick={()=>setTab(t)} style={{whiteSpace:'nowrap',textTransform:'capitalize'}}>{t}</button>)}
 </nav>
 {tab==='overview'&&<><div className="metric-grid"><article className="metric"><span>Asset</span><strong>{data.asset.internal_identifier}</strong></article><article className="metric"><span>Index</span><strong>{data.project.index_code||'—'}</strong></article><article className="metric"><span>Genre / mood</span><strong>{data.project.genre||'—'} · {data.project.mood||'—'}</strong></article><article className="metric"><span>Ownership allocated</span><strong>{total.toFixed(2)}%</strong></article></div><section className="workspace-card" style={{padding:24,marginTop:20}}><h2>Project workflow</h2><p>This is the operational home for the Project. Use the tabs above to appoint the Director, review applications, manage contributor workspaces, set milestones, assign deliverables and finalise the reserved Asset.</p></section></>}
 {tab==='director'&&<section className="workspace-card" style={{padding:24,marginTop:20}}><h2>Director</h2><p>{director?`${name(director)} is directing this Project.`:'A Director does not have to apply. Plekxa can directly appoint any registered creator; an applicant can also be accepted first and then appointed here.'}</p><div className="form-grid"><label className="field"><span>Director</span><select value={form.creator_id} onChange={e=>setForm({...form,creator_id:e.target.value})}><option value="">Select creator…</option>{data.creators.map((c:any)=><option key={c.id} value={c.id}>{name(c)}</option>)}</select></label><label className="field"><span>Asset ownership %</span><input type="number" min="0" max="100" step="0.01" value={form.ownership_percent} onChange={e=>setForm({...form,ownership_percent:Number(e.target.value)})}/></label><label className="field"><span>Director fee</span><input type="number" value={form.pay_amount} onChange={e=>setForm({...form,pay_amount:Number(e.target.value)})}/></label></div><button className="button primary" disabled={!form.creator_id} onClick={()=>void call('assign_director')}>Assign Director</button></section>}
 {tab==='applications'&&<section className="workspace-card" style={{marginTop:20}}><div className="card-head"><div><div className="card-title">Applications</div><p>Applicants see the opportunity and application questions only. Production files unlock only after acceptance/commissioning.</p></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Applicant</th><th>Portfolio</th><th>Status</th><th>Decision</th></tr></thead><tbody>{data.applications.length?data.applications.map((a:any)=><tr key={a.id}><td>{a.applicant_name||a.creator_user_id}</td><td>{a.portfolio_url?<a href={a.portfolio_url} target="_blank" rel="noreferrer">Open portfolio</a>:'—'}</td><td>{a.status}</td><td><button className="button secondary" onClick={()=>void decide(a,'shortlisted')}>Shortlist</button> <button className="button primary" onClick={()=>void decide(a,'accepted')}>Accept</button> <button className="button secondary" onClick={()=>void decide(a,'rejected')}>Reject</button></td></tr>):<tr><td colSpan={4}>No applications yet.</td></tr>}</tbody></table></div></section>}
 {tab==='contributors'&&<section className="workspace-card" style={{padding:24,marginTop:20}}><h2>Contributors & private workspaces</h2><p>A commission is not a separate kind of Project. It is a private engagement with one creator inside this Project.</p><div className="form-grid"><label className="field"><span>Creator</span><select value={form.creator_id} onChange={e=>setForm({...form,creator_id:e.target.value})}><option value="">Select creator…</option>{data.creators.map((c:any)=><option key={c.id} value={c.id}>{name(c)}</option>)}</select></label><label className="field"><span>Role</span><input value={form.role_name} onChange={e=>setForm({...form,role_name:e.target.value})}/></label><label className="field"><span>Asset ownership %</span><input type="number" min="0" max="100" step="0.01" value={form.ownership_percent} onChange={e=>setForm({...form,ownership_percent:Number(e.target.value)})}/></label><label className="field"><span>Fee</span><input type="number" value={form.pay_amount} onChange={e=>setForm({...form,pay_amount:Number(e.target.value)})}/></label></div><button className="button primary" disabled={!form.creator_id} onClick={()=>void call('commission_contributor')}>Commission creator</button><div className="table-wrap" style={{marginTop:18}}><table className="data-table"><thead><tr><th>Commission</th><th>Role</th><th>Status</th></tr></thead><tbody>{data.workspaces.map((w:any)=><tr key={w.id}><td>{w.commission_code||w.title}</td><td>{w.commission_role}</td><td>{w.status}</td></tr>)}</tbody></table></div></section>}
 {tab==='milestones'&&<section className="workspace-card" style={{padding:24,marginTop:20}}><h2>Milestones</h2><p>Milestones are schedule/checkpoints. They do not replace deliverables.</p><div className="form-grid"><label className="field"><span>Milestone</span><input value={milestone.title} onChange={e=>setMilestone({...milestone,title:e.target.value})}/></label><label className="field"><span>Due</span><input type="date" value={milestone.due_at} onChange={e=>setMilestone({...milestone,due_at:e.target.value})}/></label></div><button className="button secondary" onClick={()=>void call('add_milestone',milestone)}>Add milestone</button>{data.milestones.map((m:any)=><div className="detail" key={m.id} style={{marginTop:10}}><strong>{m.title}</strong><span>{m.due_at?new Date(m.due_at).toLocaleDateString('en-GB'):'No due date'} · {m.status}</span></div>)}</section>}
 {tab==='deliverables'&&<section className="workspace-card" style={{padding:24,marginTop:20}}><h2>Deliverables</h2><p>Deliverables are the actual outputs a commissioned creator must submit.</p><div className="form-grid"><label className="field"><span>Commission</span><select value={deliverable.workspace_id} onChange={e=>setDeliverable({...deliverable,workspace_id:e.target.value})}><option value="">Select commission…</option>{data.workspaces.filter((w:any)=>w.commission_role!=='director').map((w:any)=><option key={w.id} value={w.id}>{w.commission_code||w.title} · {w.commission_role}</option>)}</select></label><label className="field"><span>Deliverable</span><input value={deliverable.title} onChange={e=>setDeliverable({...deliverable,title:e.target.value})}/></label><label className="field"><span>Due</span><input type="date" value={deliverable.due_at} onChange={e=>setDeliverable({...deliverable,due_at:e.target.value})}/></label></div><button className="button secondary" onClick={()=>void call('add_deliverable',deliverable)}>Add deliverable</button>{data.deliverables.map((d:any)=><div className="detail" key={d.id} style={{marginTop:10}}><strong>{d.title}</strong><span>{d.review_status||d.status} · {d.due_at?new Date(d.due_at).toLocaleDateString('en-GB'):'No due date'}</span></div>)}</section>}
 {tab==='asset'&&<><section className="workspace-card" style={{marginTop:20}}><div className="card-head"><div><div className="card-title">Asset contributors</div><p>Ownership can remain below 100% during production, but cannot exceed 100%. Final approval requires exactly 100%.</p></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Contributor</th><th>Role</th><th>Asset ownership</th><th>Status</th></tr></thead><tbody>{data.contributors.length?data.contributors.map((c:any)=><tr key={c.id}><td><strong>{c.contributor_name}</strong></td><td>{c.role_name}</td><td>{Number(c.master_share||0).toFixed(2)}%</td><td>{c.allocation_status}</td></tr>):<tr><td colSpan={4}>No contributors assigned yet.</td></tr>}</tbody></table></div></section>
 <section className="workspace-card" style={{marginTop:20,padding:24}}><h2>Finalise primary Asset</h2><p>Finalise only when production is complete and contributor ownership totals exactly 100%.</p><button className="button primary" disabled={Math.abs(total-100)>0.0001} onClick={()=>void call('finalize_asset')}>Finalise {data.asset.internal_identifier}</button></section></>} </>}
