import {NextResponse} from 'next/server';
import {createClient as createAdminClient} from '@supabase/supabase-js';
import {createClient as createServerClient} from '@/lib/supabase/server';
import * as XLSX from 'xlsx';
export const dynamic='force-dynamic';
function admin(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!u||!k)throw new Error('Database not configured');return createAdminClient(u,k,{auth:{persistSession:false}})}
const pct=(v:any)=>{const n=Number(v??0);return Number.isFinite(n)?n:0}, date=(v:any)=>v?String(v).slice(0,10):'', iso=(v:any)=>v?new Date(v).toISOString():'';
export async function GET(){try{const session=await createServerClient();const{data:{user}}=await session.auth.getUser();if(!user)return NextResponse.json({error:'Not authenticated.'},{status:401});const s=admin();const{data:staff}=await s.from('staff_members').select('id,full_name,email,status').or(`auth_user_id.eq.${user.id}${user.email?`,email.ilike.${user.email}`:''}`).limit(1).maybeSingle();if(!staff||['disabled','suspended'].includes(String(staff.status).toLowerCase()))return NextResponse.json({error:'Enterprise staff access required.'},{status:403});
const [iq,aq,cq,kq,rq]=await Promise.all([s.from('plekxa_indexes').select('*').order('created_at'),s.from('asset_registry').select('*').not('index_id','is',null).order('index_assigned_at'),s.from('asset_contributors').select('*').order('created_at'),s.from('index_certificates').select('*').order('created_at'),s.from('creator_revenue_allocations').select('*').order('created_at')]);for(const q of [iq,aq,cq,kq,rq])if(q.error)throw q.error;const indexes=iq.data||[],assets=aq.data||[],contributors=cq.data||[],certificates=kq.data||[],allocations=rq.data||[];const ib=new Map(indexes.map((x:any)=>[x.id,x])),ab=new Map(assets.map((x:any)=>[x.id,x]));
const indexRows=indexes.map((i:any)=>{const aa=assets.filter((a:any)=>a.index_id===i.id);return{'Index ID':i.index_code||i.id,'Index UUID':i.id,'Name':i.name||'','Year':i.year||'','Status':i.status||'','Target Assets':i.target_asset_count??20,'Assets Reserved / Assigned':aa.length,'Position %':5,'Diversification Model':i.diversification_model||'genre_mood','Created':iso(i.created_at),'Updated':iso(i.updated_at),'Notes':i.notes||''}});
const membershipRows=assets.map((a:any)=>{const i:any=ib.get(a.index_id)||{};return{'Index ID':i.index_code||a.index_id,'Asset ID':a.internal_identifier||a.id,'Asset UUID':a.id,'Asset title':a.title||'','Genre':a.genre||'','Mood':a.mood||'','Index %':pct(a.index_participation_percentage),'Asset status':a.status||'','Assigned date':iso(a.index_assigned_at)}});
const contributorRows=contributors.filter((c:any)=>ab.has(c.asset_id)).map((c:any)=>{const a:any=ab.get(c.asset_id)||{},i:any=ib.get(a.index_id)||{},own=pct(c.master_share??c.ownership_percentage),ip=pct(a.index_participation_percentage);return{'Index ID':i.index_code||a.index_id,'Asset ID':a.internal_identifier||a.id,'Asset title':a.title||'','Contributor':c.contributor_name||c.name||'','Role':c.role_name||c.role||'','Creator/Profile ID':c.creator_id||'','Asset ownership %':own,'Asset Index %':ip,'Effective Index %':Number((ip*own/100).toFixed(6))}});
const certificateRows=certificates.map((c:any)=>{const a:any=ab.get(c.asset_id)||{},i:any=ib.get(c.index_id)||{};return{'Certificate ID':c.certificate_code||c.id,'Index ID':i.index_code||c.index_id,'Asset ID':a.internal_identifier||c.asset_id,'Asset title':a.title||'','Contributor':c.creator_name||'','Role':c.creator_role||'','Asset Index %':pct(c.asset_index_percentage),'Contributor Asset %':pct(c.contributor_asset_percentage),'Effective Index %':pct(c.effective_index_percentage??c.participation_percentage),'Effective Inclusion Date':date(c.effective_inclusion_date),'Status':c.status||'','Issuer':c.issuer||'','Issued':iso(c.issued_at||c.created_at)}});
const revenueRows=allocations.map((r:any)=>{const a:any=ab.get(r.asset_id)||{},i:any=ib.get(r.index_id)||{};return{'Index ID':i.index_code||r.index_id,'Period Start':date(r.period_start),'Period End':date(r.period_end),'Asset ID':a.internal_identifier||r.asset_id,'Asset title':a.title||'','Creator':r.creator_name||'','Asset Index %':pct(r.asset_index_percentage),'Contributor Asset %':pct(r.contributor_asset_percentage),'Effective Index %':pct(r.effective_index_percentage),'Index Period Revenue':Number(r.index_period_revenue||0),'Allocation':Number(r.amount||0),'Currency':r.currency||'','Status':r.status||'','Paid At':iso(r.paid_at),'Created':iso(r.created_at)}});
const wb=XLSX.utils.book_new(),add=(name:string,rows:any[])=>{const ws=XLSX.utils.json_to_sheet(rows.length?rows:[{'No records':'No records at export time'}]);ws['!autofilter']={ref:ws['!ref']||'A1:A1'};XLSX.utils.book_append_sheet(wb,ws,name)};add('Indexes',indexRows);add('Asset Memberships',membershipRows);add('Contributors',contributorRows);add('Certificates',certificateRows);add('Revenue Allocations',revenueRows);XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Plekxa Index Register Backup'],['Generated at',new Date().toISOString()],['Generated by',staff.full_name||user.email||staff.email||user.id],['Indexes',indexes.length],['Indexed Assets',assets.length],['Contributors',contributorRows.length],['Certificates',certificates.length],['Revenue Allocations',allocations.length]]),'Backup Info');const buffer=XLSX.write(wb,{type:'buffer',bookType:'xlsx'}),stamp=new Date().toISOString().replace(/[:.]/g,'-');return new NextResponse(buffer,{headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':`attachment; filename="Plekxa_Index_Register_${stamp}.xlsx"`,'Cache-Control':'no-store'}})}catch(e:any){return NextResponse.json({error:e?.message||'Could not export Index Register.'},{status:500})}}
