'use client';
import {useEffect,useState} from 'react';
import {uploadFileToR2} from '@/lib/browser-r2';
function fmt(n:number){if(!n)return '0 KB';if(n<1024**2)return `${(n/1024).toFixed(1)} KB`;if(n<1024**3)return `${(n/1024**2).toFixed(1)} MB`;return `${(n/1024**3).toFixed(2)} GB`}
export default function Page(){
 const [rows,setRows]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[tab,setTab]=useState('overview'),[text,setText]=useState(''),[refs,setRefs]=useState<any[]>([]),[progress,setProgress]=useState<Record<string,number>>({}),[msg,setMsg]=useState(''),[staff,setStaff]=useState<any[]>([]),[assignments,setAssignments]=useState<any[]>([]),[staffId,setStaffId]=useState(''),[assignmentRole,setAssignmentRole]=useState('team_member');
 const load=async()=>{const j=await fetch('/api/commissions',{cache:'no-store'}).then(r=>r.json());setRows(j.workspaces||[]);if(selected)setSelected((j.workspaces||[]).find((x:any)=>x.id===selected.id)||null)};
 const loadRefs=async(id:string)=>{const j=await fetch(`/api/project-reference-files?workspace_id=${id}`,{cache:'no-store'}).then(r=>r.json());setRefs(j.files||[])};
 const loadAssignments=async(id:string)=>{const j=await fetch(`/api/work-assignments?resource_type=commission&resource_id=${id}`,{cache:'no-store'}).then(r=>r.json());setStaff(j.staff||[]);setAssignments(j.assignments||[])};
 useEffect(()=>{void load()},[]);
 const choose=(w:any)=>{setSelected(w);setTab('overview');void loadRefs(w.id);void loadAssignments(w.id)};
 const assign=async()=>{if(!selected||!staffId)return;const r=await fetch('/api/work-assignments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resource_type:'commission',resource_id:selected.id,staff_id:staffId,assignment_role:assignmentRole})});const j=await r.json();setMsg(r.ok?'Personnel assigned.':j.error||'Could not assign staff');if(r.ok){setStaffId('');void loadAssignments(selected.id)}};
 const unassign=async(id:string)=>{await fetch('/api/work-assignments',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});if(selected)void loadAssignments(selected.id)};
 const send=async()=>{if(!selected||!text.trim())return;const r=await fetch('/api/commissions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspace_id:selected.id,body:text})});if(r.ok){setText('');void load()}};
 const upload=async(file:File)=>{if(!selected)return;const k=`${file.name}:${file.lastModified}`;setProgress(x=>({...x,[k]:0}));try{await uploadFileToR2('/api/project-reference-files',{workspace_id:selected.id},file,p=>setProgress(x=>({...x,[k]:p})));setMsg(`${file.name} attached. Creator can download it from Studio.`);await loadRefs(selected.id)}catch(e){setMsg(e instanceof Error?e.message:'Upload failed')}finally{setTimeout(()=>setProgress(x=>{const y={...x};delete y[k];return y}),1200)}};
 const del=async(id:string)=>{if(!confirm('Remove this reference file?'))return;const r=await fetch('/api/project-reference-files',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});if(r.ok&&selected)void loadRefs(selected.id)};
 return <><div className="page-head"><div><div className="eyebrow">Creator operations</div><h1 className="page-title">Commissions</h1><p className="page-copy">One operational workspace for each creator engagement: deliverables, files, conversation, personnel and commercial context.</p></div></div>{msg&&<div className="integration-banner pending"><span>{msg}</span></div>}
 <div style={{display:'grid',gridTemplateColumns:selected?'minmax(280px,.7fr) minmax(0,1.8fr)':'1fr',gap:20,alignItems:'start'}}>
 <div className="workspace-card"><div className="table-wrap"><table className="data-table"><thead><tr><th>Commission</th><th>Pay</th><th>Status</th></tr></thead><tbody>{rows.map(w=><tr key={w.id} onClick={()=>choose(w)} className="click-row"><td><strong>{w.commission_code||'Commission'}</strong><small className="table-sub">{w.title}</small></td><td>{w.pay_currency||'GBP'} {Number(w.pay_amount||0).toLocaleString()}</td><td>{w.status}</td></tr>)}</tbody></table></div></div>
 {selected&&<div className="workspace-card" style={{padding:28,minHeight:'70vh'}}><h2>{selected.title}</h2><p>{selected.external_partner_name?`External partner: ${selected.external_partner_name}`:'Creator Studio commission'}</p>
 <div style={{display:'flex',gap:8,flexWrap:'wrap',margin:'20px 0'}}>{['overview','deliverables','files','conversation','personnel'].map(t=><button key={t} className={`button ${tab===t?'primary':'secondary'}`} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>
 {tab==='overview'&&<section><h3>Commission overview</h3><p><strong>Code:</strong> {selected.commission_code||'—'} · <strong>Status:</strong> {selected.status||'—'} · <strong>Pay:</strong> {selected.pay_currency||'GBP'} {Number(selected.pay_amount||0).toLocaleString()}</p><p className="page-copy">This is the Enterprise counterpart of the creator's Active Project workspace. Work should be managed here rather than across disconnected screens.</p></section>}
 {tab==='deliverables'&&<section><h3>Deliverables</h3>{selected.deliverables?.length?selected.deliverables.map((d:any)=><div key={d.id} style={{border:'1px solid var(--border)',borderRadius:14,padding:16,marginBottom:12}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><strong>{d.title}</strong><span>{d.review_status||d.status}</span></div><p className="page-copy">{d.deliverable_type||'Deliverable'}{d.due_at?` · Due ${new Date(d.due_at).toLocaleDateString('en-GB')}`:''}</p><p>{d.files?.length?`${d.files.length} submitted file${d.files.length===1?'':'s'}`:'No submitted files yet.'}</p>{d.status==='submitted'&&<a className="button primary" href="/deliverables">Review submission</a>}</div>):<p>No deliverables assigned yet.</p>}<a className="button secondary" href="/deliverables">Create deliverable / open review queue</a></section>}
 {tab==='personnel'&&<section><h3>Assigned personnel</h3><p className="page-copy">Multiple Plekxa staff can work on the same commission with clear operational roles.</p><div style={{display:'flex',gap:10,flexWrap:'wrap',marginBottom:12}}><select value={staffId} onChange={e=>setStaffId(e.target.value)}><option value="">Select staff member…</option>{staff.map(x=><option key={x.id} value={x.id}>{x.full_name||x.email}{x.job_title?` — ${x.job_title}`:''}</option>)}</select><select value={assignmentRole} onChange={e=>setAssignmentRole(e.target.value)}><option value="lead">Lead</option><option value="project_manager">Project manager</option><option value="creative">Creative</option><option value="marketing">Marketing</option><option value="legal">Legal</option><option value="finance">Finance</option><option value="team_member">Team member</option></select><button className="button secondary" disabled={!staffId} onClick={()=>void assign()}>Assign</button></div>{assignments.length?assignments.map(a=><div key={a.id} style={{display:'flex',justifyContent:'space-between',gap:12,padding:'8px 0'}}><span><strong>{a.staff?.full_name||a.staff?.email||'Staff'}</strong> · {String(a.assignment_role).replaceAll('_',' ')}</span><button className="button secondary" onClick={()=>void unassign(a.id)}>Remove</button></div>):<p>No personnel assigned yet.</p>}</section>}
 {tab==='files'&&<section><h3>Project files for creator</h3><p className="page-copy">Attach beats, samples, stems, briefs, reference audio, PDFs or other working files.</p><label className="button secondary">Attach files<input hidden type="file" multiple onChange={e=>{for(const f of Array.from(e.target.files||[]))void upload(f);e.currentTarget.value=''}}/></label>{Object.entries(progress).map(([k,p])=><div key={k} style={{marginTop:10}}><span>{k.split(':')[0]} · {p}%</span><progress value={p} max={100} style={{width:'100%'}}/></div>)}{refs.map(f=><div key={f.id} style={{display:'flex',justifyContent:'space-between',gap:12,padding:'9px 0'}}>{f.download_url?<a href={f.download_url} target="_blank" rel="noreferrer">{f.file_name} <small>({fmt(Number(f.size_bytes||0))})</small></a>:<span>{f.file_name} <small>({fmt(Number(f.size_bytes||0))}) · Missing from R2 — re-upload required</small></span>}<button className="button secondary" onClick={()=>void del(f.id)}>Remove</button></div>)}</section>}
 {tab==='conversation'&&<section><h3>Conversation</h3><div style={{border:'1px solid var(--border)',borderRadius:14,padding:18,minHeight:260,maxHeight:520,overflowY:'auto',marginBottom:14}}>{selected.messages?.length?selected.messages.map((m:any)=><div key={m.id} style={{maxWidth:'82%',marginLeft:m.sender_side==='enterprise'?'auto':0,marginBottom:12,padding:'10px 13px',borderRadius:12,background:'var(--surface-2,#f4f4f4)'}}><strong>{m.sender_side==='enterprise'?'Plekxa':'Creator'}</strong><div>{m.body}</div></div>):<p>No messages yet.</p>}</div><textarea style={{width:'100%'}} rows={5} value={text} onChange={e=>setText(e.target.value)} placeholder="Write a message…"/><div style={{display:'flex',justifyContent:'flex-end',marginTop:10}}><button className="button primary" disabled={!text.trim()} onClick={()=>void send()}>Send message</button></div></section>}
 </div>}</div></>}
