import Link from 'next/link';
import MetricCards from '@/components/MetricCards';
import {ArrowRight,ArrowUpRight,CalendarDays,CheckCircle,CircleDollarSign,Clock,FolderKanban,Sparkles,Users} from '@/components/icons';
const attention=[
 {title:'Approve Q3 project stipends',meta:'Finance · $16,970 net payable',status:'Approval due',href:'/finance'},
 {title:'Review Stories and Moonlight rights',meta:'Registry · 4 assets incomplete',status:'High priority',href:'/assets'},
 {title:'Decide 8 creator applications',meta:'Creator Success · Stories and Moonlight',status:'Today',href:'/applications'},
 {title:'Publish Bittersweet launch article',meta:'Content Studio · Scheduled 5 Aug',status:'Ready',href:'/newsroom'},
];
const activity=[['Creator approved','Amara Nwosu was verified','6 min'],['Project moved','Bittersweet entered final review','24 min'],['Asset registered','Midnight Interlude · PX-A-00418','1 hr'],['Campaign scheduled','Creator acquisition Nigeria','3 hr']];
export default function Dashboard(){return <>
<div className="page-head"><div><div className="eyebrow">Enterprise command centre</div><h1 className="page-title">Good evening, Anthony.</h1><p className="page-copy">One operating view across Plekxa Group, Plekxa Studio and the audience platform.</p></div><Link className="button primary" href="/projects">Open operations <ArrowUpRight size={15}/></Link></div>
<MetricCards items={[{label:'Active projects',value:'12',change:'4 accepting applications'},{label:'Pending approvals',value:'27',change:'6 require executive action'},{label:'Active creators',value:'184',change:'+18 this month'},{label:'Net payable',value:'$42,780',change:'Across 3 open batches'}]}/>
<div className="dashboard-grid">
<section className="card attention-card"><div className="card-head"><div><div className="card-title">Work requiring attention</div><p>Decisions that are blocking another team or release.</p></div><span className="status warn">4 urgent</span></div><div className="attention-list">{attention.map(item=><Link href={item.href} key={item.title}><div><strong>{item.title}</strong><span>{item.meta}</span></div><div className="attention-action"><em>{item.status}</em><ArrowRight size={17}/></div></Link>)}</div></section>
<section className="card pulse-card"><div className="card-head"><div><div className="card-title">Company pulse</div><p>Progress across core operating areas.</p></div></div><div className="pulse-list"><div><span><FolderKanban/>Projects on track</span><strong>83%</strong><i><b style={{width:'83%'}}/></i></div><div><span><Users/>Creator verification</span><strong>76%</strong><i><b style={{width:'76%'}}/></i></div><div><span><Sparkles/>Experience completion</span><strong>64%</strong><i><b style={{width:'64%'}}/></i></div><div><span><CircleDollarSign/>Payout readiness</span><strong>71%</strong><i><b style={{width:'71%'}}/></i></div></div></section>
</div>
<div className="dashboard-grid lower">
<section className="card"><div className="card-head"><div><div className="card-title">Portfolio timeline</div><p>Key milestones over the next 90 days.</p></div><Link href="/projects">View all</Link></div><div className="timeline-list"><div><span className="timeline-date">05 Aug</span><i/><div><strong>Bittersweet campaign launch</strong><small>Marketing · Release preparation</small></div></div><div><span className="timeline-date">18 Aug</span><i/><div><strong>Bittersweet release</strong><small>Experience · Scheduled</small></div></div><div><span className="timeline-date">30 Sep</span><i/><div><strong>Stories and Moonlight delivery</strong><small>Project · In production</small></div></div><div><span className="timeline-date">12 Nov</span><i/><div><strong>Midnight Reflections release</strong><small>Experience · In development</small></div></div></div></section>
<section className="card"><div className="card-head"><div><div className="card-title">Live activity</div><p>Latest changes across the operating system.</p></div><Link href="/activity">Audit log</Link></div><div className="activity-list">{activity.map(([a,b,c])=><div key={b}><span className="activity-icon"><CheckCircle size={16}/></span><div><strong>{a}</strong><small>{b}</small></div><time>{c}</time></div>)}</div></section>
</div>
<div className="quick-launch"><Link href="/creators"><Users/><span><strong>Add creator</strong><small>Create and verify a profile</small></span></Link><Link href="/projects"><FolderKanban/><span><strong>Create project</strong><small>Build a complete workspace</small></span></Link><Link href="/experiences"><Sparkles/><span><strong>Build experience</strong><small>Assemble audience content</small></span></Link><Link href="/finance"><CircleDollarSign/><span><strong>Run payout</strong><small>Prepare an approval batch</small></span></Link></div>
</>}
